plugins {
    id 'com.android.application'
}

android {
    namespace 'com.matheuspaiim.librasstudio'
    compileSdk 35

    defaultConfig {
        applicationId "com.matheuspaiim.librasstudio"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "0.2.1"
    }

    flavorDimensions += "edition"
    productFlavors {
        create("public") {
            dimension "edition"
            applicationId "com.matheuspaiim.librasstudio"
        }
        create("personal") {
            dimension "edition"
            applicationId "com.matheuspaiim.librasstudio.personal"
            versionNameSuffix "-personal"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
