const APP_VERSION="0.5.34";
const cfg=window.LIBRAS_STUDIO_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const nativeParams=new URLSearchParams(location.search);
const IS_NATIVE_ANDROID=nativeParams.get("native")==="android";
const NATIVE_APK_BUILD=nativeParams.get("apk")||"";
if(IS_NATIVE_ANDROID)document.documentElement.classList.add("native-app");
let sb,S={session:null,signs:[],cats:[],reviews:[],study:[],catalog:null,catalogStats:null,phraseResults:[],queue:[],i:0,explore:null,librasLabCandidates:[]};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const title=s=>{s=String(s||"").trim().replace(/\s+/g," ");return s?s[0].toLocaleUpperCase("pt-BR")+s.slice(1).toLocaleLowerCase("pt-BR"):s};
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove("show"),2500)}
function go(v){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+v)?.classList.add("active");$$("nav [data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$$(".side-nav [data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#more")?.classList.add("hidden");window.scrollTo(0,0);if(v==="progress")renderProgressPage();if(v==="library")library();if(v==="explore")exploreCats();if(v==="libraslab")refreshLibrasLab()}
const REMEMBERED_USER_KEY="ls-remembered-user-v1",PENDING_PREFIX="ls-pending-v1:",CACHE_PREFIX="ls-full-v2:";
function rememberedUser(){try{return JSON.parse(localStorage.getItem(REMEMBERED_USER_KEY)||"null")}catch{return null}}
function rememberSession(session){let u=session?.user;if(!u?.id)return;localStorage.setItem(REMEMBERED_USER_KEY,JSON.stringify({id:u.id,email:u.email||""}))}
function forgetRememberedUser(){localStorage.removeItem(REMEMBERED_USER_KEY);localStorage.removeItem("ls-full")}
function offlineSession(user){return user?.id?{user:{id:user.id,email:user.email||""},offline:true}:null}
function activeUserId(){return S.session?.user?.id||rememberedUser()?.id||""}
function userCacheKey(id=activeUserId()){return id?CACHE_PREFIX+id:""}
function pendingKey(id=activeUserId()){return id?PENDING_PREFIX+id:""}
function authUI(){let on=!!S.session;$("#auth").classList.toggle("hidden",on);$("#app").classList.toggle("hidden",!on);if(on)$("#account").textContent="☁️ "+(S.session.user.email||"Conta")}
function cache(){let key=userCacheKey();if(!key)return;try{localStorage.setItem(key,JSON.stringify({signs:S.signs,cats:S.cats,reviews:S.reviews,study:S.study,updated_at:new Date().toISOString()}))}catch(e){console.warn("cache local",e)}}
function cached(userId=activeUserId()){try{let key=userCacheKey(userId),raw=key?localStorage.getItem(key):null;if(!raw&&userId){raw=localStorage.getItem("ls-full");if(raw){localStorage.setItem(key,raw);localStorage.removeItem("ls-full")}}let x=JSON.parse(raw||"{}");S.signs=x.signs||[];S.cats=x.cats||[];S.reviews=x.reviews||[];S.study=x.study||[];return !!raw}catch{return false}}
function pendingOps(){let key=pendingKey();if(!key)return[];try{return JSON.parse(localStorage.getItem(key)||"[]")}catch{return[]}}
function setPendingOps(ops){let key=pendingKey();if(!key)return;try{if(ops.length)localStorage.setItem(key,JSON.stringify(ops));else localStorage.removeItem(key)}catch(e){console.warn("fila offline",e)}}
function queuePending(type,key,row){let ops=pendingOps(),id=type+":"+key,next={type,key,row,queued_at:new Date().toISOString()},i=ops.findIndex(x=>x.type+":"+x.key===id);if(i>=0)ops[i]=next;else ops.push(next);setPendingOps(ops)}
async function flushPending(){let ops=pendingOps();if(!ops.length)return 0;let remain=[],done=0;for(let op of ops){try{let res;if(op.type==="study")res=await sb.from("study_progress").upsert(op.row,{onConflict:"user_id,lesson_id"});else if(op.type==="review")res=await sb.from("review_state").upsert(op.row,{onConflict:"user_id,norm"});else continue;if(res.error)throw res.error;done++}catch(e){console.warn("sincronização pendente",op,e);remain.push(op)}}setPendingOps(remain);if(remain.length)throw new Error("pending-sync-failed");return done}
function localStatus(text){let el=$("#sync-status");if(el)el.textContent=text}
async function sync({silent=false}={}){
  if(!S.session)return;
  cached();render();
  if(!navigator.onLine){localStatus("📴 offline · dados locais");return}
  if(window.__lsSyncing)return;
  window.__lsSyncing=true;
  if(!silent)localStatus("sincronizando…");
  const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error("sync-timeout")),8000));
  try{
    await flushPending();
    let[c,s,r,p]=await Promise.race([Promise.all([
      sb.from("categories").select("*").is("deleted_at",null).order("sort_order"),
      sb.from("signs").select("*").is("deleted_at",null).order("name"),
      sb.from("review_state").select("*").is("deleted_at",null),
      sb.from("study_progress").select("*")
    ]),timeout]);
    for(let x of[c,s,r,p])if(x.error)throw x.error;
    S.cats=c.data||[];S.signs=s.data||[];S.reviews=r.data||[];S.study=p.data||[];
    cache();render();localStatus("☁️ sincronizado");
    signMedia().then(()=>{cache();render();cacheLibraryVideos()}).catch(e=>console.warn("mídias",e));
  }catch(e){
    console.error("sync",e);cached();localStatus("📴 offline · dados locais");render();
  }finally{window.__lsSyncing=false}
}
async function signMedia(){for(let s of S.signs){if(s.media_path&&!s.media_url){let z=await sb.storage.from("sign-videos").createSignedUrl(s.media_path,86400);if(z.data?.signedUrl)s.media_url=z.data.signedUrl}}}
const LIBRARY_MEDIA_CACHE="libras-studio-library-v1",MEDIA_CACHE_PENDING=new Set;
function nativeMediaAvailable(){return !!(IS_NATIVE_ANDROID&&window.LibrasMedia&&typeof window.LibrasMedia.getCachedVideoUrl==="function")}
function nativeCachedVideoUrl(studioId){if(!nativeMediaAvailable()||!studioId)return"";try{return window.LibrasMedia.getCachedVideoUrl(String(studioId))||""}catch{return""}}
function libraryVideoUrl(item){return nativeCachedVideoUrl(item?.studio_id)||vurl(item)}
async function cacheWebLibraryVideo(url){if(!url||!("caches"in window))return false;try{let cache=await caches.open(LIBRARY_MEDIA_CACHE),req=new Request(url,{mode:"no-cors",cache:"no-store"});if(await cache.match(req,{ignoreVary:true}))return true;let res=await fetch(req);if(!res||(res.type!=="opaque"&&!res.ok))return false;await cache.put(req,res.clone());return true}catch(e){console.warn("cache web de vídeo",e);return false}}
async function cacheLibraryVideo(item,{replace=false}={}){let id=item?.studio_id,url=vurl(item);if(!id||!url||!navigator.onLine)return false;if(nativeMediaAvailable()){if(!replace&&nativeCachedVideoUrl(id))return true;if(MEDIA_CACHE_PENDING.has(id))return true;MEDIA_CACHE_PENDING.add(id);try{if(replace&&typeof window.LibrasMedia.replaceCachedVideo==="function")window.LibrasMedia.replaceCachedVideo(String(id),url);else window.LibrasMedia.cacheVideo(String(id),url);return true}catch(e){MEDIA_CACHE_PENDING.delete(id);console.warn("cache nativo de vídeo",e);return false}}if(MEDIA_CACHE_PENDING.has(id))return true;MEDIA_CACHE_PENDING.add(id);try{return await cacheWebLibraryVideo(url)}finally{MEDIA_CACHE_PENDING.delete(id)}}
function cacheLibraryVideos(){if(!navigator.onLine)return;for(let item of S.signs)if(vurl(item))cacheLibraryVideo(item)}
function deleteCachedLibraryVideo(item){let id=item?.studio_id,url=vurl(item);MEDIA_CACHE_PENDING.delete(id);if(nativeMediaAvailable()&&id&&typeof window.LibrasMedia.deleteCachedVideo==="function"){try{window.LibrasMedia.deleteCachedVideo(String(id))}catch{}}if(url&&"caches"in window)caches.open(LIBRARY_MEDIA_CACHE).then(c=>c.delete(url,{ignoreVary:true})).catch(()=>{})}
window.addEventListener("librasstudio-media-cache",e=>{let d=e.detail||{};if(d.studioId)MEDIA_CACHE_PENDING.delete(String(d.studioId))});
function render(){const steps=[["home",home],["libraryCats",libraryCats],["library",library],["reviewCats",reviewCats],["study",study],["exploreCats",exploreCats],["progress",renderProgressPage]];let errors=[];for(const [name,fn] of steps){try{fn()}catch(e){errors.push({name,error:e});console.error("render:"+name,e)}}try{if(window.LSHydrateIcons)LSHydrateIcons(document)}catch(e){errors.push({name:"icons",error:e});console.error("render:icons",e)}return errors}
function unique(){let m=new Map;S.signs.forEach(s=>{if(!m.has(s.norm))m.set(s.norm,s)});return[...m.values()]}
function rmap(){return Object.fromEntries(S.reviews.map(x=>[x.norm,x]))}

const HOME_CATS=[
  ["Pessoas","Pessoas e pronomes"],["Alimentação","Alimentos e bebidas"],["Animais","Animais"],
  ["Trabalho","Trabalho e profissões"],["Casa","Casa e objetos"],["Sentimentos","Sentimentos e emoções"],["Natureza","Natureza e clima"]
];
function localDateKey(v){let d=v instanceof Date?v:new Date(v);if(!v||Number.isNaN(d.getTime()))return"";let p=n=>String(n).padStart(2,"0");return d.getFullYear()+"-"+p(d.getMonth()+1)+"-"+p(d.getDate())}
function addDays(d,n){let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()+n);return x}
function activityDateSet(){
  let set=new Set;
  S.study.forEach(x=>{if(x.completed)addActivity(x.completed_at||x.updated_at)});
  S.reviews.forEach(x=>addActivity(x.last_reviewed_at));
  S.signs.forEach(x=>addActivity(x.created_at));
  return set;
  function addActivity(v){let k=localDateKey(v);if(k)set.add(k)}
}
function streakInfo(){
  let set=activityDateSet(),keys=[...set].sort(),best=0,run=0,prev=null;
  for(let k of keys){let d=new Date(k+"T12:00:00");if(prev&&Math.round((d-prev)/86400000)===1)run++;else run=1;best=Math.max(best,run);prev=d}
  let today=new Date();today.setHours(12,0,0,0);let cursor=set.has(localDateKey(today))?today:addDays(today,-1),current=0;
  while(set.has(localDateKey(cursor))){current++;cursor=addDays(cursor,-1)}
  return{set,best,current};
}
function studySnapshot(){
  let L=window.LIBRAS_STUDY_CONTENT||[],m=smap(),done=L.filter(x=>m[x.id]?.completed),mods=[...new Set(L.map(x=>x.module))];
  let moduleRows=mods.map(name=>{let lessons=L.filter(x=>x.module===name),n=lessons.filter(x=>m[x.id]?.completed).length;return{name,total:lessons.length,done:n,complete:n===lessons.length}});
  let completedModules=moduleRows.filter(x=>x.complete).length,lastId=localStorage.getItem("ls-last-lesson")||"",current=L.find(x=>x.id===lastId&&!m[x.id]?.completed)||L.find(x=>!m[x.id]?.completed)||null;
  let currentIndex=current?L.findIndex(x=>x.id===current.id):-1,next=currentIndex>=0?L[currentIndex+1]||null:null,currentModule=current?moduleRows.find(x=>x.name===current.module):null;
  let pct=Math.round(done.length/Math.max(1,L.length)*100),modulePct=currentModule?Math.round(currentModule.done/Math.max(1,currentModule.total)*100):pct;
  return{L,m,done,moduleRows,completedModules,current,next,pct,modulePct};
}
function moduleLabel(name){return({"Fundamentos":"Fundamentos da Libras","Expressão e gramática":"Expressão e gramática","Espaço e fluidez":"Espaço e fluidez","Conversa e texto":"Conversa e fluência"})[name]||name}
function openStudyLesson(id){
  if(id)localStorage.setItem("ls-last-lesson",id);
  let snap=studySnapshot(),lesson=snap.L.find(x=>x.id===id);
  if(lesson){let mods=$("#study-modules");if(mods)mods.dataset.active=lesson.module}
  go("study");study();
  requestAnimationFrame(()=>document.getElementById("lesson-"+id)?.scrollIntoView({behavior:"smooth",block:"start"}));
}
function openHomeCategory(cat){go("explore");S.explore=cat;exploreCats();setTimeout(()=>openCat(cat),0)}
function home(){
  if(!$("#home-sign-count"))return;
  let m=rmap(),now=Date.now(),u=unique(),due=0,fresh=0,reviewed=0;
  u.forEach(x=>{let r=m[x.norm];if(!r)fresh++;else{if(r.last_reviewed_at)reviewed++;if(r.due_at&&new Date(r.due_at).getTime()<=now)due++}});
  let snap=studySnapshot(),streak=streakInfo(),cats=new Set(u.map(x=>x.category_name).filter(Boolean)),withVideo=u.filter(vurl).length;
  let email=S.session?.user?.email||"",name=(email.split("@")[0]||"estudante").split(/[._-]/)[0];name=name?name[0].toUpperCase()+name.slice(1):"estudante";
  $("#home-user-name").textContent=name;$("#profile-name").textContent="Olá, "+name+"!";$("#profile-avatar").textContent=(name.slice(0,2)||"LS").toUpperCase();
  $("#home-sign-count").textContent=u.length;$("#home-cat-count").textContent=cats.size;$("#home-library-health").textContent=(u.length?Math.round(withVideo/u.length*100):0)+"%";
  $("#home-due-count").textContent=due;$("#home-new-count").textContent=fresh;$("#home-reviewed-count").textContent=reviewed;
  $("#home-learned").textContent=u.length+" sinais";$("#home-best-streak").textContent=streak.best+" "+(streak.best===1?"dia":"dias");
  $("#home-lessons-done").textContent=snap.done.length;$("#home-review-activity").textContent=reviewed;
  $("#home-overall-pct").textContent=snap.pct+"%";$("#home-overall-ring").style.setProperty("--pct",snap.pct);
  $("#home-module-count").textContent=snap.completedModules+" de "+snap.moduleRows.length;let mp=Math.round(snap.completedModules/Math.max(1,snap.moduleRows.length)*100);$("#home-module-pct").textContent=mp+"%";$("#home-module-ring").style.setProperty("--pct",mp);
  $("#home-sequence-list").innerHTML=snap.moduleRows.map((x,i)=>'<div class="sequence-item '+(x.complete?"done":(!x.complete&&snap.moduleRows.findIndex(y=>!y.complete)===i?"current":""))+'"><span class="dot">'+(x.complete?"✓":i+1)+'</span><span>'+(x.complete?"":snap.moduleRows.findIndex(y=>!y.complete)===i?"Próximo: ":"")+esc(moduleLabel(x.name))+'</span></div>').join("");
  $("#home-study-days").innerHTML=[-6,-5,-4,-3,-2,-1,0].map(n=>{let d=addDays(new Date(),n),on=streak.set.has(localDateKey(d)),lab=d.toLocaleDateString("pt-BR",{weekday:"short"}).replace(".","");return '<div class="study-day '+(on?"active":"")+'"><div class="day-dot">'+(on?LSIcon("streak","icon-sm"):"")+'</div><small>'+lab+'</small></div>'}).join("");
  $("#home-explore-cats").innerHTML=HOME_CATS.map(([label,cat])=>'<button class="shortcut-cat" data-home-cat="'+esc(cat)+'">'+LSCategoryIcon(cat)+'<b>'+esc(label)+'</b><small>'+((window.LIBRAS_EXPLORE_DATA||{})[cat]?.terms?.length||0)+' sinais-base</small></button>').join("");
  document.querySelectorAll("[data-home-cat]").forEach(b=>b.onclick=()=>openHomeCategory(b.dataset.homeCat));
  let cur=snap.current;
  $("#home-current-module").textContent=cur?moduleLabel(cur.module):"Trilha concluída";
  $("#home-current-title").textContent=cur?cur.title:"Você concluiu todas as aulas";
  $("#home-current-summary").textContent=cur?cur.summary:"Continue revisando e explorando novos sinais.";
  $("#home-current-progress").style.width=snap.modulePct+"%";$("#home-current-progress-label").textContent=snap.modulePct+"% do módulo";
  $("#home-next-title").textContent=snap.next?snap.next.title:"Nenhuma aula pendente";$("#home-next-meta").textContent=snap.next?moduleLabel(snap.next.module):"Trilha atual concluída";
  $("#home-continue").disabled=!cur;$("#home-continue").onclick=()=>cur&&openStudyLesson(cur.id);
  if(window.LSHydrateIcons)LSHydrateIcons($("#home"));
}
function renderProgressPage(){
  let root=$("#tracking-page");if(!root)return;let snap=studySnapshot(),streak=streakInfo(),u=unique(),reviewed=S.reviews.filter(x=>x.last_reviewed_at).length;
  let days=[-6,-5,-4,-3,-2,-1,0].map(n=>{let d=addDays(new Date(),n),on=streak.set.has(localDateKey(d)),label=d.toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit"});return '<div class="day '+(on?"active":"")+'">'+(on?LSIcon("streak","icon-sm"):"<span>○</span>")+'<b>'+label+'</b></div>'}).join("");
  root.innerHTML='<div class="surface tracking-wide"><div class="dash-card-head"><div class="dash-card-title">'+LSIcon("streak")+'<h3>Constância dos últimos 7 dias</h3></div></div><div class="week-calendar">'+days+'</div></div>'+
  '<div class="surface"><div class="dash-card-title">'+LSIcon("tracking")+'<h3>Avanço na trilha</h3></div><div class="tracking-main" style="margin-top:14px"><div class="ring" style="--pct:'+snap.pct+'"><span>'+snap.pct+'%</span></div><div class="tracking-stats"><div class="tracking-stat">'+LSIcon("lesson","icon-sm")+'<div><b>'+snap.done.length+'</b><small>de '+snap.L.length+' aulas concluídas</small></div></div><div class="tracking-stat">'+LSIcon("reviewActivity","icon-sm")+'<div><b>'+reviewed+'</b><small>sinais já revisados</small></div></div></div></div></div>'+
  '<div class="surface"><div class="dash-card-title">'+LSIcon("learned")+'<h3>Aprendizado</h3></div><div class="progress-pills" style="margin-top:14px"><div class="progress-pill">'+LSIcon("learned","icon-sm")+'<div><small>Sinais na biblioteca</small><b>'+u.length+'</b></div></div><div class="progress-pill">'+LSIcon("best","icon-sm")+'<div><small>Melhor sequência</small><b>'+streak.best+' dias</b></div></div><div class="progress-pill">'+LSIcon("streak","icon-sm")+'<div><small>Sequência atual</small><b>'+streak.current+' dias</b></div></div><div class="progress-pill">'+LSIcon("sequence","icon-sm")+'<div><small>Módulos concluídos</small><b>'+snap.completedModules+'/'+snap.moduleRows.length+'</b></div></div></div></div>'+
  '<div class="surface tracking-wide"><div class="dash-card-title">'+LSIcon("sequence")+'<h3>Progresso por módulo</h3></div><div class="sequence-list" style="margin-top:14px">'+snap.moduleRows.map((x,i)=>'<div class="sequence-item '+(x.complete?"done":"")+'"><span class="dot">'+(x.complete?"✓":i+1)+'</span><span>'+esc(moduleLabel(x.name))+' · '+x.done+'/'+x.total+' aulas</span></div>').join("")+'</div></div>';
  if(window.LSHydrateIcons)LSHydrateIcons(root);
}
const SRC=[["signbank","SignBank / UFSC","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_ufsc_signbank.csv"],["vlibrasil","V-LIBRASIL / UFPE","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_vlibrasil.csv"],["goiasnacional","GoiásLibras · base nacional","./data/goias_nacional.csv"],["ines","INES / Acessibilidade Brasil","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_acessibilidade_brasil.csv"],["ufv","UFV","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_ufv.csv"],["usp","USP","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_usp.csv"],["spread","Spread the Sign","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_spreadthesign.csv"]];
const SOURCE_RANK={signbank:0,ufv:1,usp:2,spread:3,vlibrasil:4,goiasnacional:5,ines:6};
const CURATED_SIGN_MEDIA={
  obrigado:[
    {label:"Obrigado",url:"https://libras.cin.ufpe.br/storage/videos/20210127054726_6011d15eafba7.mp4",source_id:"vlibrasil",source_name:"V-LIBRASIL / UFPE"},
    {label:"Obrigado",url:"https://libras.cin.ufpe.br/storage/videos/20210505103828_60929fd499aaa.mp4",source_id:"vlibrasil",source_name:"V-LIBRASIL / UFPE"},
    {label:"Obrigado",url:"https://libras.cin.ufpe.br/storage/videos/20210619023531_60ce2ae3ef11a.mp4",source_id:"vlibrasil",source_name:"V-LIBRASIL / UFPE"}
  ]
};
function csvLine(l){let a=[],x="",q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c=='"'){if(q&&l[i+1]=='"'){x+='"';i++}else q=!q}else if(c===","&&!q){a.push(x);x=""}else x+=c}a.push(x);return a}
function catalogKeys(label){let raw=String(label||"").trim(),base=raw.replace(/\d+$/,"").trim(),keys=new Set;const add=x=>{let k=norm(String(x||"").replace(/\d+$/,""));if(k)keys.add(k)};add(base);add(base.replace(/\([^)]*\)/g," "));base.split(/\s+ou\s+|\/|:/i).forEach(add);return[...keys]}async function sourceText(url){try{if("caches"in window){let c=await caches.open("libras-studio-catalog-v2"),hit=await c.match(url);if(hit)return hit.text();let r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);await c.put(url,r.clone());return r.text()}}catch(e){console.warn("cache catálogo",e)}let r=await fetch(url);if(!r.ok)throw new Error("HTTP "+r.status);return r.text()}async function catalog(){if(S.catalog)return S.catalog;let map={},rows=0;const all=await Promise.all(SRC.map(async([id,name,url])=>{try{return{id,name,text:await sourceText(url)}}catch(e){console.warn(name,e);return{id,name,text:""}}}));for(let src of all){let ls=src.text.split(/\r?\n/);for(let i=1;i<ls.length;i++){if(!ls[i])continue;let a=csvLine(ls[i]),label=a[0]?.trim(),u=a[1]?.trim();if(!label||!u)continue;rows++;let opt={label,url:u.replace(/^http:/,"https:"),source_id:src.id,source_name:src.name},options=[opt];if(src.id==="ines"){let m=opt.url.match(/\/palavras\/videos\/([^?#]+)/i);if(m)options.unshift({label,url:"https://goiaslibras.educacao.go.gov.br/api/media/ines/palavras/videos/"+m[1],source_id:"goiasnacional",source_name:"GoiásLibras · base nacional"})}for(let k of catalogKeys(label)){let arr=map[k]??=[];for(let candidate of options)if(!arr.some(x=>x.url===candidate.url))arr.push(candidate);map[k]=arr}}}for(let k in map)map[k].sort((a,b)=>(SOURCE_RANK[a.source_id]??99)-(SOURCE_RANK[b.source_id]??99));S.catalog=map;S.catalogStats={rows,labels:Object.keys(map).length,multiword:Object.keys(map).filter(k=>k.includes(" ")).length,sources:all.filter(x=>x.text).length};return map}
const opts=n=>{let k=norm(n),arr=[...((S.catalog||{})[k]||[]),...(CURATED_SIGN_MEDIA[k]||[])],seen=new Set;return arr.filter(x=>x.url&&!seen.has(x.url)&&seen.add(x.url)).sort((a,b)=>(SOURCE_RANK[a.source_id]??99)-(SOURCE_RANK[b.source_id]??99))};
const MEDIA_HEALTH_KEY="ls-media-health-v1",MEDIA_OK_TTL=12*60*60*1000,MEDIA_FAIL_TTL=20*60*1000;
function mediaHealth(){try{return JSON.parse(localStorage.getItem(MEDIA_HEALTH_KEY)||"{}")}catch{return{}}}
function setMediaHealth(url,ok){if(!url)return;let h=mediaHealth();h[url]={ok:!!ok,at:Date.now()};let entries=Object.entries(h).sort((a,b)=>(b[1]?.at||0)-(a[1]?.at||0)).slice(0,600);try{localStorage.setItem(MEDIA_HEALTH_KEY,JSON.stringify(Object.fromEntries(entries)))}catch{}}
function knownMediaHealth(url){let x=mediaHealth()[url];if(!x)return null;let ttl=x.ok?MEDIA_OK_TTL:MEDIA_FAIL_TTL;if(Date.now()-(x.at||0)>ttl)return null;return!!x.ok}
function probeVideo(url,timeout=4500){if(!url)return Promise.resolve(false);let known=knownMediaHealth(url);if(known!==null)return Promise.resolve(known);return new Promise(resolve=>{let v=document.createElement("video"),done=false,timer;const finish=ok=>{if(done)return;done=true;clearTimeout(timer);v.onloadedmetadata=v.oncanplay=v.onerror=null;try{v.pause();v.removeAttribute("src");v.load()}catch{}setMediaHealth(url,ok);resolve(ok)};v.preload="metadata";v.muted=true;v.playsInline=true;v.onloadedmetadata=()=>finish(true);v.oncanplay=()=>finish(true);v.onerror=()=>finish(false);timer=setTimeout(()=>finish(false),timeout);try{v.src=url;v.load()}catch{finish(false)}})}
function mediaCandidateKey(x){if(x?.youtube)return"yt:"+x.youtube;let u=String(x?.url||"");if(!u)return"";if(x?.source_id==="ines"||x?.source_id==="goiasnacional"){let m=u.match(/\/palavras\/videos\/([^?#]+)/i);if(m)return"ines:"+m[1].toLowerCase()}return u}function dedupeCandidates(list){let seen=new Set;return(list||[]).filter(x=>{let k=mediaCandidateKey(x);if(!k||seen.has(k))return false;seen.add(k);return true})}
async function validateCandidates(list,{timeout=4000,max=12,keep=8}={}){let items=dedupeCandidates(list).slice(0,max);let checks=await Promise.all(items.map(async x=>x.youtube?true:probeVideo(x.url,timeout)));return items.filter((x,i)=>checks[i]).slice(0,keep)}
async function firstPlayable(list,{timeout=4000,max=12}={}){let items=dedupeCandidates(list).slice(0,max),knownGood=items.find(x=>x.youtube||knownMediaHealth(x.url)===true);if(knownGood)return knownGood;for(let x of items){if(x.youtube)return x;if(await probeVideo(x.url,timeout))return x}return null}
function allMediaCandidates(name){let list=[];try{list.push(...phraseCuratedExact(name))}catch{}list.push(...opts(name));return dedupeCandidates(list)}
async function preferredSignMedia(name,fallbackStudioId=""){let saved=fallbackStudioId?S.signs.find(x=>x.studio_id===fallbackStudioId):null,local=saved?nativeCachedVideoUrl(saved.studio_id):"";if(local)return{url:local,source_id:saved.source_id||"saved",source_name:(saved.source_name||"Biblioteca")+" · offline"};if(!navigator.onLine){if(saved&&!IS_NATIVE_ANDROID&&vurl(saved))return{url:vurl(saved),source_id:saved.source_id||"saved",source_name:saved.source_name||"Biblioteca"};return null}try{let list=await signOptions(name),picked=await firstPlayable(list,{timeout:4000,max:20});if(!picked){list=await signOptions(name,{refresh:true});picked=await firstPlayable(list,{timeout:4000,max:20})}if(picked)return picked}catch(e){console.warn("mídia principal",e)}if(saved){let url=vurl(saved);if(url&&await probeVideo(url,3500))return{url,source_id:saved.source_id||"saved",source_name:saved.source_name||"Biblioteca"}}return null}
async function playPreferredSign(name,fallbackStudioId=""){modal('<h2>'+esc(title(name))+'</h2><p>🔎 Abrindo o sinal principal…</p>');let picked=await preferredSignMedia(name,fallbackStudioId);if(!picked)return modal('<h2>'+esc(title(name))+'</h2><p>Nenhum vídeo disponível foi encontrado agora.</p>');let id="preferred-"+Date.now(),sid=fallbackStudioId||"";modal('<h2>'+esc(title(name))+'</h2><video data-video-id="'+id+'" '+(sid?'data-studio-id="'+esc(sid)+'" ':'')+'controls autoplay loop playsinline preload="metadata" src="'+esc(picked.url)+'"></video>'+speedTools(id));bindSpeeds($("#modal-body"));bindVideoFallbacks($("#modal-body"),name)}

async function repairMedia(studioId,candidate){if(!studioId||!candidate?.url||!S.session)return;let patch={source_id:candidate.source_id||"fallback",source_name:candidate.source_name||"Fonte alternativa",source_url:candidate.url,media_url:candidate.url,updated_at:new Date().toISOString()};try{let{error}=await sb.from("signs").update(patch).eq("studio_id",studioId);if(error)throw error;let item=S.signs.find(x=>x.studio_id===studioId);if(item){Object.assign(item,patch);cacheLibraryVideo(item,{replace:true})}cache()}catch(e){console.warn("reparo de mídia",e)}}
function catFor(n){let k=norm(n);for(let[c,d]of Object.entries(window.LIBRAS_EXPLORE_DATA||{}))if(d.terms.some(x=>norm(x)===k))return c;return"Outros"}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
async function save(name,o,cat=null,origin="catalog"){let n=norm(name),row={user_id:S.session.user.id,studio_id:uuid(),name:title(name),norm:n,variant_no:S.signs.filter(x=>x.norm===n).length+1,variant_key:"mobile|"+n+"|"+norm(o.url),category_name:cat||catFor(name),category_source:cat?"explore":"auto",category_tags:"[]",source_id:o.source_id,source_name:o.source_name,source_url:o.url,source_label:o.label,origin,media_url:o.url,updated_at:new Date().toISOString()},{data,error}=await sb.from("signs").insert(row).select().single();if(error)throw error;S.signs.push(data);cache();render();cacheLibraryVideo(data);return data}
async function createSign(){let names=$("#create-name").value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!names.length)return toast("Digite o nome do sinal.");$("#create-name").value="";if(names.length===1){let n=names[0];$("#create-result").innerHTML='<div class="result">🔎 Buscando e verificando os vídeos…</div>';await catalog();let options=opts(n);if(!options.length)return $("#create-result").innerHTML='<div class="result">🔎 Não encontrei correspondência exata.</div>';let picked=await firstPlayable(options,{timeout:3800,max:10});if(!picked)return $("#create-result").innerHTML='<div class="result"><b>⚠️ Encontrei '+options.length+' gravação(ões), mas nenhuma carregou agora.</b><p>O Studio não vai salvar um vídeo quebrado. Tente novamente mais tarde ou veja as variações.</p></div>';try{let r=await save(n,picked);$("#create-result").innerHTML='<div class="result phrase-ok"><b>✅ '+esc(r.name)+'</b><video controls loop playsinline src="'+esc(r.media_url)+'"></video></div>';toast("Salvo com vídeo verificado ☁️")}catch(e){console.error(e);toast("Não consegui salvar.")}return}$("#create-result").innerHTML='<div class="result">🔎 Processando '+names.length+' sinais…</div>';await catalog();let ok=[],fail=[];for(let n of names){try{let options=opts(n),picked=options.length?await firstPlayable(options,{timeout:3200,max:10}):null;if(!picked){fail.push(n);continue}await save(n,picked,null,"batch");ok.push(n)}catch(e){console.error("lote",n,e);fail.push(n)}}$("#create-result").innerHTML='<div class="result"><b>✅ '+ok.length+' de '+names.length+' sinais salvos</b>'+(fail.length?'<p>Não encontrados: '+esc(fail.join(", "))+'</p>':'')+'</div>';toast(ok.length+" sinal(is) adicionado(s) ☁️")}
async function variants(){let names=$("#create-name").value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!names.length)return toast("Digite um sinal primeiro.");if(names.length>1)return toast("Para ver variações, deixe apenas um sinal no campo.");let n=names[0];await openAvailableVariants(n,catFor(n))}
async function uploadVideo(f){if(!f)return;let names=$("#create-name").value.split(/\n/).map(x=>x.trim()).filter(Boolean);if(!names.length)return toast("Digite o nome antes.");if(names.length>1)return toast("Para enviar um vídeo, deixe apenas um sinal no campo.");let n=names[0];let path=S.session.user.id+"/"+Date.now()+"_"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_"),up=await sb.storage.from("sign-videos").upload(path,f);if(up.error)return toast("Falha no upload.");let row={user_id:S.session.user.id,studio_id:uuid(),name:title(n),norm:norm(n),variant_no:S.signs.filter(x=>x.norm===norm(n)).length+1,variant_key:"upload|"+path,category_name:catFor(n),category_source:"auto",category_tags:"[]",source_id:"mobile_upload",source_name:"Vídeo meu",origin:"mobile_upload",media_path:path,updated_at:new Date().toISOString()},{data,error}=await sb.from("signs").insert(row).select().single();if(error)return toast(error.message);let z=await sb.storage.from("sign-videos").createSignedUrl(path,86400);data.media_url=z.data?.signedUrl;S.signs.push(data);cache();render();cacheLibraryVideo(data);toast("Vídeo enviado ☁️")}
const STOP=new Set(["a","o","as","os","de","da","do","das","dos","em","no","na","nos","nas","para","pra","por","com","e","um","uma","ao","aos","à","às","eu","voce"]);
function words(x){return norm(x).split(" ").filter(w=>w&&!STOP.has(w))}
function similarity(a,b){let A=new Set(words(a)),B=new Set(words(b));if(!A.size||!B.size)return 0;let inter=[...A].filter(x=>B.has(x)).length;if(!inter)return 0;let score=inter/Math.max(A.size,B.size),na=norm(a),nb=norm(b);if(na===nb)score+=2;else if(na.includes(nb)||nb.includes(na))score+=.55;return score}
function phraseCuratedExact(q){let k=norm(q);return(window.LIBRAS_PHRASE_DATA||[]).filter(p=>norm(p.text)===k||(p.aliases||[]).some(a=>norm(a)===k)).map(p=>({name:p.text,label:p.text,url:p.url||"",youtube:p.youtube||"",source_id:p.source_id||"singlibras_phrase",source_name:p.source||"Sing Libras",page:p.page||"",kind:"real"}))}
function phraseCatalogExact(q){return opts(q).map(o=>({name:o.label.replace(/\d+$/,"").trim(),label:o.label,url:o.url,source_id:o.source_id,source_name:o.source_name,kind:"real"}))}
function phraseSimilar(q){let pool=[];for(let p of(window.LIBRAS_PHRASE_DATA||[])){let sc=Math.max(similarity(q,p.text),...(p.aliases||[]).map(a=>similarity(q,a)),0);if(sc>.2)pool.push({name:p.text,label:p.text,url:p.url||"",youtube:p.youtube||"",source_id:p.source_id||"singlibras_phrase",source_name:p.source||"Sing Libras",page:p.page||"",kind:"real",score:sc})}for(let k of Object.keys(S.catalog||{})){if(!k.includes(" "))continue;let sc=similarity(q,k);if(sc>.2){let o=opts(k)[0];if(o)pool.push({name:o.label.replace(/\d+$/,"").trim(),label:o.label,url:o.url,source_id:o.source_id,source_name:o.source_name,kind:"real",score:sc})}}let seen=new Set;return pool.sort((a,b)=>b.score-a.score).filter(x=>{let k=norm(x.name)+"|"+x.url+"|"+x.youtube;if(seen.has(k))return false;seen.add(k);return true}).slice(0,8)}
async function translateGloss(text){try{let ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),8000),r=await fetch("https://traducao2.vlibras.gov.br/translate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text}),signal:ctl.signal});clearTimeout(t);if(!r.ok)return"";let raw=await r.text();try{let j=JSON.parse(raw);return j.traducao||raw}catch{return raw}}catch{return""}}
function phraseRow(x,i,similar=false){let canSave=!!x.url;return '<div class="phrase-row"><div><b>'+esc(x.name)+'</b><small>'+esc(x.source_name)+(similar?' · semelhante':' · gravação real')+' · ✓ vídeo verificado</small></div><div class="phrase-actions"><button class="soft" data-phrase-view="'+i+'">▶ Ver</button>'+(canSave?'<button class="primary" data-phrase-save="'+i+'">＋ Salvar</button>':"")+'</div></div>'}
function bindPhraseResults(){document.querySelectorAll("[data-phrase-view]").forEach(b=>b.onclick=()=>previewPhrase(+b.dataset.phraseView));document.querySelectorAll("[data-phrase-save]").forEach(b=>b.onclick=()=>savePhraseResult(+b.dataset.phraseSave));let v=$("#vlibras-phrase");if(v)v.onclick=()=>previewVLibras($("#phrase-name").value.trim())}
function previewPhrase(i){let x=S.phraseResults[i];if(!x)return;if(x.youtube){modal('<h2>'+esc(x.name)+'</h2><div class="yt-wrap"><iframe src="https://www.youtube.com/embed/'+encodeURIComponent(x.youtube)+'?playsinline=1" title="'+esc(x.name)+'" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen></iframe></div><p>'+esc(x.source_name)+' · vídeo verificado pela fonte</p>');return}let id="phrase-"+i;modal('<h2>'+esc(x.name)+'</h2><video data-video-id="'+id+'" controls autoplay loop playsinline preload="metadata" src="'+esc(x.url)+'"></video>'+speedTools(id)+'<p>'+esc(x.source_name)+' · ✓ vídeo verificado</p>');bindSpeeds($("#modal-body"));bindVideoFallbacks($("#modal-body"),x.name)}
async function savePhraseResult(i){let x=S.phraseResults[i];if(!x?.url)return;try{await save(x.name,{url:x.url,label:x.label||x.name,source_id:x.source_id,source_name:x.source_name},"Frases","phrase_complete");toast("Frase salva e sincronizada ☁️")}catch(e){console.error(e);toast("Não consegui salvar a frase.")}}
async function ensureVLibras(){if(window.vlibras?.translateAndPlay)return true;if(!window.VLibras?.Widget){await new Promise((resolve,reject)=>{let old=document.querySelector('script[data-vlibras]');if(old){old.addEventListener("load",resolve,{once:true});setTimeout(resolve,1200);return}let sc=document.createElement("script");sc.src="https://vlibras.gov.br/app/vlibras-plugin.js";sc.dataset.vlibras="1";sc.onload=resolve;sc.onerror=reject;document.body.appendChild(sc)});if(window.VLibras?.Widget)new window.VLibras.Widget({rootPath:"https://vlibras.gov.br/app",showButton:false,position:"R"})}window.VLibrasWidget?.open?.();for(let i=0;i<60;i++){if(window.vlibras?.translateAndPlay)return true;await new Promise(r=>setTimeout(r,250))}return false}
async function previewVLibras(text){if(!text)return;toast("Abrindo tradução automática do VLibras…");try{if(await ensureVLibras())await window.vlibras.translateAndPlay(text);else toast("VLibras não carregou agora.")}catch(e){console.error(e);toast("Não consegui abrir o VLibras.")}}
async function phrase(){let n=$("#phrase-name").value.trim();if(!n)return toast("Digite uma frase.");$("#phrase-result").innerHTML='<div class="result">🔎 Procurando e testando gravações reais…</div>';await catalog();let rawExact=[...phraseCuratedExact(n),...phraseCatalogExact(n)],seen=new Set;rawExact=rawExact.filter(x=>{let k=(x.url||x.youtube||"")+"|"+norm(x.name);if(seen.has(k))return false;seen.add(k);return true});let exact=await validateCandidates(rawExact,{timeout:3800,max:14,keep:8}),similar=[];if(!exact.length){$("#phrase-result").innerHTML='<div class="result">🔎 A frase exata não carregou. Testando produções próximas…</div>';similar=await validateCandidates(phraseSimilar(n),{timeout:3300,max:8,keep:5})}let gloss=await translateGloss(n);S.phraseResults=[...exact,...similar];let html='<div class="phrase-meta">🩺 O Studio testou os arquivos antes de mostrá-los · '+(S.catalogStats?.sources||6)+' bases conectadas</div>';if(exact.length){html+='<div class="result phrase-ok"><b>✅ '+exact.length+' gravação(ões) funcionando</b><p>São produções contínuas reais. Links que falharam foram descartados automaticamente.</p></div>'+exact.map((x,i)=>phraseRow(x,i,false)).join("")}else{html+='<div class="result"><b>🔎 Nenhuma gravação exata funcional apareceu agora.</b><p>Links quebrados ou servidores fora do ar foram escondidos. O Studio não monta sinais isolados para fingir uma frase.</p></div>';if(similar.length)html+=similar.map((x,i)=>phraseRow(x,i,true)).join("");else html+='<p class="empty-note">Também não encontrei uma produção semelhante com vídeo funcionando neste momento.</p>'}html+='<div class="auto-translation"><b>🤖 Tradução automática oficial do VLibras</b><p>É um fallback com avatar, separado das gravações humanas.'+(gloss?' Glosa sugerida: <code>'+esc(gloss)+'</code>.':'')+'</p><button id="vlibras-phrase" class="soft wide">▶ Ver esta frase no VLibras</button></div>';$("#phrase-result").innerHTML=html;bindPhraseResults()}
async function batch(){let ns=$("#batch-text").value.split(/\n|,/).map(x=>x.trim()).filter(Boolean),ok=0,fail=[];await catalog();for(let n of ns){let o=opts(n);if(!o.length){fail.push(n);continue}try{await save(n,o[0],null,"batch");ok++}catch{fail.push(n)}}$("#batch-result").innerHTML='<div class="result"><b>✅ '+ok+' salvos</b>'+(fail.length?'<p>Não encontrados: '+esc(fail.join(", "))+'</p>':"")+"</div>"}
function exploreCats(){let q=norm($("#explore-search")?.value),D=window.LIBRAS_EXPLORE_DATA||{};$("#explore-cats").innerHTML=Object.entries(D).filter(([c,d])=>!q||norm(c+" "+d.description).includes(q)).map(([c,d])=>'<button data-cat="'+esc(c)+'" class="'+(S.explore===c?"active":"")+'">'+LSCategoryIcon(c)+" "+esc(c)+"</button>").join("");$$("[data-cat]").forEach(b=>b.onclick=()=>openCat(b.dataset.cat))}
async function signOptions(name,{refresh=false}={}){if(refresh)S.catalog=null;await catalog();return opts(name)}
async function openCat(c){
  S.explore=c;exploreCats();
  let panel=$("#explore-panel"),d=(window.LIBRAS_EXPLORE_DATA||{})[c];
  if(!d)return;
  let optionMap=new Map,playable=new Set,verificationFailed=false;
  const renderRows=(loading=false)=>{
    let owned=new Set(S.signs.map(x=>x.norm));
    let visible=d.terms.map((t,i)=>({t,i})).filter(x=>loading||playable.has(norm(x.t)));
    let rows=visible.map(({t,i})=>{
      let o=optionMap.get(norm(t))||[],has=owned.has(norm(t));
      return '<div class="explore-row"><div class="explore-row-copy"><b>'+esc(title(t))+'</b>'+(has?'<small>✓ na biblioteca</small>':loading?'<small>verificando vídeo…</small>':'')+'</div><div class="explore-row-actions">'+(loading?'<span class="explore-owned-mark">…</span>':(has?'<span class="explore-owned-mark">✓</span>':'<button data-add="'+i+'" aria-label="Adicionar '+esc(title(t))+'">＋</button>')+'<button class="soft explore-variants-btn" data-explore-variants="'+i+'">Variações</button><button class="explore-play-btn" data-explore-play="'+i+'" aria-label="Reproduzir '+esc(title(t))+'">▶</button>')+'</div></div>';
    }).join("");
    let empty=!loading&&!rows?'<div class="surface center"><p>'+(verificationFailed?'Não consegui verificar os vídeos desta categoria agora.':'Nenhum sinal com vídeo disponível nesta categoria agora.')+'</p></div>':'';
    panel.innerHTML='<div class="card explore-category-head"><h3>'+LSCategoryIcon(c)+' <span>'+esc(c)+'</span></h3><p>'+esc(d.description)+'</p></div>'+rows+empty;
    $$("[data-add]").forEach(b=>b.onclick=async()=>{let t=d.terms[+b.dataset.add],o=optionMap.get(norm(t))||[];try{let picked=await firstPlayable(o,{timeout:3500,max:10});if(!picked){playable.delete(norm(t));renderRows(false);return toast("Este vídeo deixou de responder e o sinal foi ocultado.");}await save(t,picked,c,"category_explorer");renderRows(false)}catch(e){console.error(e);toast("Falha ao adicionar")}});
    $$("[data-explore-variants]").forEach(b=>b.onclick=()=>openAvailableVariants(d.terms[+b.dataset.exploreVariants],c));
    $$("[data-explore-play]").forEach(b=>b.onclick=async()=>{let t=d.terms[+b.dataset.explorePlay],picked=await preferredSignMedia(t);if(!picked){playable.delete(norm(t));renderRows(false);return toast("Vídeo indisponível. O sinal foi ocultado do Explorar.");}let id="explore-"+Date.now();modal('<h2>'+esc(title(t))+'</h2><video data-video-id="'+id+'" controls autoplay loop playsinline preload="metadata" src="'+esc(picked.url)+'"></video>'+speedTools(id));bindSpeeds($("#modal-body"));bindVideoFallbacks($("#modal-body"),t)});
  };
  renderRows(true);requestAnimationFrame(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}));
  try{
    await catalog();
    d.terms.forEach(t=>optionMap.set(norm(t),opts(t)));
    let cursor=0,workers=Math.min(6,d.terms.length);
    await Promise.all(Array.from({length:workers},async()=>{
      while(cursor<d.terms.length){
        let t=d.terms[cursor++],o=optionMap.get(norm(t))||[];
        if(!o.length)continue;
        try{if(await firstPlayable(o,{timeout:3200,max:10}))playable.add(norm(t))}catch(e){console.warn("verificação explorar",t,e)}
      }
    }));
  }catch(e){console.error(e);verificationFailed=true}
  renderRows(false);requestAnimationFrame(()=>panel.scrollIntoView({behavior:"smooth",block:"start"}));
}
function smap(){return Object.fromEntries(S.study.map(x=>[x.lesson_id,x]))}
function study(){let L=window.LIBRAS_STUDY_CONTENT||[],m=smap(),done=L.filter(x=>m[x.id]?.completed).length;$("#study-count").textContent=done+" de "+L.length+" aulas";$("#study-pct").textContent=Math.round(done/Math.max(1,L.length)*100)+"%";let mods=[...new Set(L.map(x=>x.module))],a=$("#study-modules").dataset.active||"";$("#study-modules").innerHTML='<button data-mod="" class="'+(!a?"active":"")+'">Todas</button>'+mods.map(x=>'<button data-mod="'+esc(x)+'" class="'+(a===x?"active":"")+'">'+esc(moduleLabel(x))+"</button>").join("");$$("[data-mod]").forEach(b=>b.onclick=()=>{$("#study-modules").dataset.active=b.dataset.mod;study()});let q=norm($("#study-search").value),F=L.filter(x=>(!a||x.module===a)&&(!q||norm(x.title+" "+x.summary).includes(q)));$("#study-list").innerHTML=F.map(x=>'<article class="lesson" id="lesson-'+x.id+'"><small>'+LSIcon("lesson","icon-sm")+" "+esc(moduleLabel(x.module))+" · "+esc(x.level)+'</small><h3>'+esc(x.title)+'</h3><p>'+esc(x.summary)+'</p>'+x.sections.map(sec=>'<h4>'+esc(sec[0])+'</h4><p>'+esc(sec[1])+"</p>").join("")+'<div class="practice"><b>Prática</b><p>'+esc(x.practice)+'</p></div><ul>'+x.take.map(t=>"<li>"+esc(t)+"</li>").join("")+"</ul>"+(x.resources||[]).map(r=>'<a class="resource" href="'+esc(r[1])+'" target="_blank">↗ '+esc(r[0])+"</a>").join("")+'<div class="continue-actions"><button class="soft" data-focus-lesson="'+x.id+'">Continuar desta aula</button><label class="complete"><input type="checkbox" data-lesson="'+x.id+'" '+(m[x.id]?.completed?"checked":"")+'> Aula concluída</label></div></article>').join("");$$("[data-focus-lesson]").forEach(b=>b.onclick=()=>{localStorage.setItem("ls-last-lesson",b.dataset.focusLesson);toast("Aula marcada para continuar depois.")});$$("[data-lesson]").forEach(c=>c.onchange=()=>saveLesson(c.dataset.lesson,c.checked));if(window.LSHydrateIcons)LSHydrateIcons($("#study"))}
async function saveLesson(id,v){let row={user_id:S.session.user.id,lesson_id:id,completed:v,completed_at:v?new Date().toISOString():null,updated_at:new Date().toISOString()},i=S.study.findIndex(x=>x.lesson_id===id);if(i>=0)S.study[i]=row;else S.study.push(row);let L=window.LIBRAS_STUDY_CONTENT||[],idx=L.findIndex(x=>x.id===id);if(v){let nx=L.slice(idx+1).find(x=>!smap()[x.id]?.completed);if(nx)localStorage.setItem("ls-last-lesson",nx.id)}else localStorage.setItem("ls-last-lesson",id);cache();render();if(!navigator.onLine){queuePending("study",id,row);localStatus("📴 offline · alterações salvas");return}try{let{error}=await sb.from("study_progress").upsert(row,{onConflict:"user_id,lesson_id"});if(error)throw error}catch(e){console.warn("progresso offline",e);queuePending("study",id,row);localStatus("📴 salvo no aparelho")}}
function vurl(s){return s.media_url||(s.source_url&&/\.mp4($|\?)/i.test(s.source_url)?s.source_url.replace(/^http:/,"https:"):"")}
function libraryCats(){let sel=$("#library-cat");if(!sel)return;let previous=sel.value,cs=[...new Set([...S.cats.map(x=>x.name),...S.signs.map(x=>x.category_name)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));sel.replaceChildren(new Option("Todas as categorias",""));for(let c of cs){let meta=S.cats.find(x=>x.name===c),label=(meta?.emoji?meta.emoji+" ":"")+c;sel.add(new Option(label,c))}sel.value=cs.includes(previous)?previous:""}
function speedTools(id){return '<div class="video-tools"><span>Velocidade</span>'+[.25,.5,.75,1,1.25].map(x=>'<button type="button" class="speed-btn '+(x===1?"active":"")+'" data-speed="'+x+'" data-video="'+id+'">'+x+'x</button>').join("")+'</div>'}
function bindSpeeds(root=document){root.querySelectorAll(".speed-btn").forEach(b=>b.onclick=()=>{let v=root.querySelector('[data-video-id="'+b.dataset.video+'"]')||document.querySelector('[data-video-id="'+b.dataset.video+'"]');if(!v)return;v.playbackRate=+b.dataset.speed;root.querySelectorAll('.speed-btn[data-video="'+b.dataset.video+'"]').forEach(x=>x.classList.toggle("active",x===b))})}
function fmtInterval(d){d=Number(d||0);let min=Math.round(d*1440);if(min<60)return min+" min";let h=d*24;if(h<24)return (Math.round(h*10)/10).toString().replace(".0","")+" h";if(d<30)return (Math.round(d*10)/10).toString().replace(".0","")+" "+(Math.abs(d-1)<.01?"dia":"dias");let mo=d/30;if(mo<12)return (Math.round(mo*10)/10)+" meses";let y=d/365;return (Math.round(y*10)/10)+" anos"}
async function bindVideoFallbacks(root,name){let videos=[...root.querySelectorAll("video")];for(let v of videos){let current=()=>v.currentSrc||v.src;v.onloadedmetadata=()=>setMediaHealth(current(),true);v.onerror=async()=>{if(v.dataset.fallbackBusy==="1")return;v.dataset.fallbackBusy="1";let bad=current();setMediaHealth(bad,false);if(!navigator.onLine){let note=document.createElement("small");note.className="video-fallback-note";note.textContent="📴 Este vídeo não está disponível offline neste aparelho.";v.after(note);v.dataset.fallbackBusy="0";return}try{await catalog();let tried=new Set((v.dataset.tried||"").split("|").filter(Boolean));tried.add(bad);let candidates=allMediaCandidates(name).filter(x=>x.url&&!tried.has(x.url)),next=await firstPlayable(candidates,{timeout:3500,max:10});if(next){tried.add(next.url);v.dataset.tried=[...tried].join("|");v.src=next.url;v.load();let old=v.parentElement?.querySelector(".source-switch");if(old)old.remove();let note=document.createElement("small");note.className="video-fallback-note source-switch";note.textContent="🔄 Fonte alternativa: "+(next.source_name||"outra base");v.after(note);await repairMedia(v.dataset.studioId,next);v.dataset.fallbackBusy="0";return}let note=document.createElement("small");note.className="video-fallback-note";note.textContent="⚠️ As fontes disponíveis para este vídeo estão fora do ar agora.";v.after(note)}finally{v.dataset.fallbackBusy="0"}}}}


const LIBRARY_OPEN_KEY="ls-library-open-v1";
function libraryOpenSet(){try{return new Set(JSON.parse(localStorage.getItem(LIBRARY_OPEN_KEY)||"[]"))}catch{return new Set}}
function saveLibraryOpenSet(set){try{localStorage.setItem(LIBRARY_OPEN_KEY,JSON.stringify([...set]))}catch{}}
function bindLibraryCategories(){document.querySelectorAll("[data-cat-toggle]").forEach(btn=>btn.onclick=()=>{let section=btn.closest(".lib-category"),body=section?.querySelector(".cat-collapse"),name=btn.dataset.catToggle;if(!body||!name)return;let next=btn.getAttribute("aria-expanded")!=="true";btn.setAttribute("aria-expanded",String(next));body.classList.toggle("open",next);section.classList.toggle("open",next);let open=libraryOpenSet();next?open.add(name):open.delete(name);saveLibraryOpenSet(open)})}
function library(){let q=norm($("#library-search").value),cat=$("#library-cat")?.value||"",g={},open=libraryOpenSet();S.signs.filter(s=>(!cat||s.category_name===cat)&&(!q||norm(s.name+" "+s.category_name).includes(q))).forEach(s=>(g[s.category_name||"Outros"]??=[]).push(s));$("#library-list").innerHTML=Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0],"pt-BR")).map(([c,it])=>{let meta=S.cats.find(x=>x.name===c),expanded=!!q||!!cat||open.has(c),count=new Set(it.map(x=>x.norm)).size,rows=it.map(x=>'<div class="lib-row" data-row-id="'+x.studio_id+'" role="button" tabindex="0" aria-label="Selecionar '+esc(x.name)+'"><input type="checkbox" class="library-check" data-sel="'+x.studio_id+'" aria-label="Selecionar '+esc(x.name)+'"><div><b>'+esc(x.name)+'</b></div>'+'<div class="lib-row-actions"><button type="button" class="library-variants-btn" data-library-variants="'+esc(x.norm||norm(x.name))+'" aria-label="Ver variações de '+esc(x.name)+'">Variações</button><button class="library-play-btn" data-preferred-play="'+esc(x.name)+'" data-fallback-id="'+x.studio_id+'" aria-label="Reproduzir '+esc(x.name)+'">▶</button></div></div>').join("");return '<section class="lib-category '+(expanded?"open":"")+'"><button type="button" class="cat-head cat-toggle" data-cat-toggle="'+esc(c)+'" aria-expanded="'+String(expanded)+'"><span class="cat-head-main"><span>'+LSCategoryIcon(c)+esc(c)+'</span></span><span class="cat-head-right"><span class="cat-count">'+count+'</span><span class="cat-toggle-mark">⌄</span></span></button><div class="cat-collapse '+(expanded?"open":"")+'"><div class="cat-items">'+rows+"</div></div></section>"}).join("")||'<div class="card center"><p>Nenhum sinal nesta categoria.</p></div>';bindLibraryCategories();bindLibraryRows();document.querySelectorAll("[data-preferred-play]").forEach(b=>b.onclick=e=>{e.stopPropagation();playPreferredSign(b.dataset.preferredPlay,b.dataset.fallbackId||"")});document.querySelectorAll("[data-library-variants]").forEach(b=>b.onclick=e=>{e.stopPropagation();openLibraryVariants(b.dataset.libraryVariants)})}
async function openAvailableVariants(name,categoryName){modal('<h2>Variações de '+esc(title(name))+'</h2><p>🔎 Verificando quais vídeos estão disponíveis…</p>');try{let candidates=await signOptions(name),all=await validateCandidates(candidates,{timeout:4200,max:30,keep:20});if(!all.length){candidates=await signOptions(name,{refresh:true});all=await validateCandidates(candidates,{timeout:4200,max:30,keep:20})}if(!all.length)return modal('<h2>Variações de '+esc(title(name))+'</h2><p>Nenhum vídeo disponível foi encontrado agora.</p>');let savedUrls=new Set(S.signs.filter(x=>(x.norm||norm(x.name))===norm(name)).map(vurl).filter(Boolean));modal('<h2>Variações de '+esc(title(name))+'</h2><div class="library-variants">'+all.map((x,i)=>'<div class="library-variant"><video controls loop playsinline preload="metadata" src="'+esc(x.url)+'"></video><button type="button" class="soft wide" data-save-available-variant="'+i+'" '+(savedUrls.has(x.url)?'disabled':'')+'>'+(savedUrls.has(x.url)?'✓ Já salva':'＋ Salvar esta variação')+'</button></div>').join("")+'</div>');$$("[data-save-available-variant]").forEach(b=>b.onclick=async()=>{let candidate=all[+b.dataset.saveAvailableVariant];if(!candidate)return;b.disabled=true;try{await save(name,candidate,categoryName||catFor(name),"catalog");b.textContent="✓ Salva";toast("Variação adicionada à biblioteca")}catch(e){console.error(e);b.disabled=false;toast("Não consegui salvar esta variação.")}})}catch(e){console.error(e);modal('<h2>Variações de '+esc(title(name))+'</h2><p>Não consegui consultar as variações agora.</p>')}}
async function openLibraryVariants(signNorm){let first=S.signs.find(x=>(x.norm||norm(x.name))===signNorm);if(first)await openAvailableVariants(first.name,first.category_name)}
async function openOrRepairLibrarySign(studioId){
  let item=S.signs.find(x=>x.studio_id===studioId);if(!item)return;
  let local=nativeCachedVideoUrl(item.studio_id),url=local||vurl(item);
  if(IS_NATIVE_ANDROID&&!navigator.onLine&&!local)return toast("Este vídeo ainda não foi baixado neste aparelho. Conecte-se uma vez para o Studio salvá-lo offline.");
  if(!url){
    toast("Procurando um vídeo para "+item.name+"…");
    try{await catalog();let picked=await firstPlayable(allMediaCandidates(item.name),{timeout:3500,max:12});if(picked){await repairMedia(item.studio_id,picked);url=picked.url;library()}else return toast("Ainda não encontrei um vídeo funcionando para "+item.name+".")}catch(e){console.error(e);return toast("Não consegui consultar as fontes agora.")}
  }
  let id="lib-"+item.studio_id;modal("<h2>"+esc(item.name)+'</h2><video data-video-id="'+id+'" data-studio-id="'+esc(item.studio_id)+'" controls autoplay loop playsinline preload="metadata" src="'+esc(url)+'"></video>'+speedTools(id)+'<p>'+esc(item.source_name||"Libras Studio")+"</p>");bindSpeeds($("#modal-body"));bindVideoFallbacks($("#modal-body"),item.name);
}
function bindLibraryRows(){document.querySelectorAll(".lib-row").forEach(row=>{let cb=row.querySelector("[data-sel]");if(!cb)return;let paint=()=>row.classList.toggle("selected",cb.checked);paint();cb.onchange=paint;row.onclick=e=>{if(e.target.closest("button,input,a,select,label"))return;cb.checked=!cb.checked;paint()};row.onkeydown=e=>{if((e.key==="Enter"||e.key===" ")&&!e.target.closest("button,input,a,select,label")){e.preventDefault();cb.checked=!cb.checked;paint()}}})}
const selected=()=>$$("[data-sel]:checked").map(x=>x.dataset.sel);
async function newCat(){let n=prompt("Nome da categoria:");if(!n)return;let e=prompt("Emoji:","🧩")||"🧩",row={user_id:S.session.user.id,name:title(n),emoji:e,sort_order:999,is_custom:true,is_hidden:false,updated_at:new Date().toISOString()},{data,error}=await sb.from("categories").insert(row).select().single();if(error)return toast(error.message);S.cats.push(data);render()}
async function move(){let ids=selected();if(!ids.length)return toast("Selecione sinais.");let names=S.cats.map(x=>x.name),c=prompt("Mover para qual categoria?\n\n"+names.join("\n"));if(!names.includes(c))return;let{error}=await sb.from("signs").update({category_name:c,category_source:"manual",updated_at:new Date().toISOString()}).in("studio_id",ids);if(error)return toast(error.message);S.signs.forEach(x=>{if(ids.includes(x.studio_id))x.category_name=c});library()}
async function del(){let ids=selected();if(!ids.length||!confirm("Excluir "+ids.length+" item(ns)?"))return;let removed=S.signs.filter(x=>ids.includes(x.studio_id)),now=new Date().toISOString(),{error}=await sb.from("signs").update({deleted_at:now,updated_at:now}).in("studio_id",ids);if(error)return toast(error.message);removed.forEach(deleteCachedLibraryVideo);S.signs=S.signs.filter(x=>!ids.includes(x.studio_id));cache();render()}
function reviewCats(){let s=$("#review-cat"),v=s.value,cs=[...new Set(S.signs.map(x=>x.category_name).filter(Boolean))].sort();s.innerHTML='<option value="">Todas</option>'+cs.map(x=>'<option>'+esc(x)+"</option>").join("");s.value=v}
function next(rate,c){let reps=c?.reps||0,e=c?.ease||2.5,iv=+c?.interval_days||0,d=0,l=c?.lapses||0,n=reps;if(rate==="again"){d=10/1440;e=Math.max(1.3,e-.2);l++}if(rate==="hard"){d=reps?Math.max(1,iv*1.2):.25;e=Math.max(1.3,e-.15);n++}if(rate==="good"){d=reps===0?1:reps===1?3:Math.max(1,iv*e);n++}if(rate==="easy"){e=Math.min(3.5,e+.15);d=reps?Math.max(2,iv*(e+.3)):4;n++}return{interval_days:d,ease:e,reps:n,lapses:l,due_at:new Date(Date.now()+d*864e5).toISOString()}}
function queue(){let c=$("#review-cat").value,mode=$("#review-mode").value,m=rmap(),now=Date.now(),due=[],fresh=[];unique().filter(s=>!c||s.category_name===c).forEach(s=>{let r=m[s.norm];if(!r)fresh.push(s);else if(r.due_at&&new Date(r.due_at).getTime()<=now)due.push(s)});let out=mode==="due"?due:mode==="new"?fresh:[...due,...fresh],lim=$("#review-limit").value;return lim==="all"?out:out.slice(0,+lim)}
function card(){let s=S.queue[S.i];if(!s){$("#review-card").classList.add("hidden");$("#review-done").classList.remove("hidden");return}$("#review-card").classList.remove("hidden");$("#review-done").classList.add("hidden");$("#review-name").textContent=s.name;$("#review-media").classList.add("hidden");$("#ratings").classList.add("hidden");$("#reveal").classList.remove("hidden");let current=rmap()[s.norm];["again","hard","good","easy"].forEach(k=>{let el=document.querySelector('[data-time="'+k+'"]');if(el)el.textContent=fmtInterval(next(k,current).interval_days)});let vs=S.signs.filter(x=>x.norm===s.norm&&libraryVideoUrl(x));$("#review-media").innerHTML=vs.length?vs.map((v,i)=>{let id="rev-"+S.i+"-"+i;return '<video data-video-id="'+id+'" data-studio-id="'+esc(v.studio_id)+'" controls loop playsinline preload="metadata" src="'+esc(libraryVideoUrl(v))+'"></video>'+speedTools(id)+'<small>'+(vs.length>1?"Variação "+(i+1)+" · ":"")+esc(v.source_name||"")+"</small>"}).join(""):"<p>Vídeo indisponível.</p>";bindSpeeds($("#review-media"));bindVideoFallbacks($("#review-media"),s.name)}
async function rate(r){let s=S.queue[S.i],row={user_id:S.session.user.id,norm:s.norm,...next(r,rmap()[s.norm]),last_rating:r,last_reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()},i=S.reviews.findIndex(x=>x.norm===s.norm);if(i>=0)S.reviews[i]=row;else S.reviews.push(row);S.i++;cache();render();card();if(!navigator.onLine){queuePending("review",s.norm,row);localStatus("📴 offline · revisão salva");return}try{let{error}=await sb.from("review_state").upsert(row,{onConflict:"user_id,norm"});if(error)throw error}catch(e){console.warn("revisão offline",e);queuePending("review",s.norm,row);localStatus("📴 salvo no aparelho")}}
function modal(h){$("#modal-body").innerHTML=h;$("#modal").classList.remove("hidden")}
async function clearStudioRuntime(){if("caches"in window){let ks=await caches.keys();await Promise.all(ks.filter(k=>k.startsWith("libras-studio-mobile-")||k.startsWith("libras-studio-catalog-")).map(k=>caches.delete(k)))}if("serviceWorker"in navigator){let regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.filter(r=>r.scope.includes("/libras-studio/")).map(r=>r.unregister()))}}
async function forceAppUpdate(){try{localStorage.removeItem(MEDIA_HEALTH_KEY)}catch{}toast("Buscando atualização…");try{let remote=APP_VERSION;try{let r=await fetch("./version.json?t="+Date.now(),{cache:"no-store"});if(r.ok){let v=await r.json();remote=v.version||remote}}catch{}await clearStudioRuntime();location.replace("./?updated="+encodeURIComponent(remote)+"&t="+Date.now())}catch(e){console.error(e);toast("Não consegui atualizar agora.")}}
async function checkAppUpdate(){if(IS_NATIVE_ANDROID)return false;try{let r=await fetch("./version.json?t="+Date.now(),{cache:"no-store"});if(!r.ok)return false;let v=await r.json();if(v.version&&v.version!==APP_VERSION){await clearStudioRuntime();location.replace("./?updated="+encodeURIComponent(v.version)+"&t="+Date.now());return true}return false}catch(e){return false}}
async function setupServiceWorker(){if(IS_NATIVE_ANDROID)return;if(!("serviceWorker"in navigator))return;try{let reg=await navigator.serviceWorker.register("./sw.js?v="+APP_VERSION,{updateViaCache:"none"});await reg.update();navigator.serviceWorker.addEventListener("controllerchange",()=>{if(!window.__lsReloading){window.__lsReloading=true;location.reload()}})}catch(e){console.warn("SW",e)}}

const LL_UI_WORDS=new Set(["continuar","voltar","proximo","pular","sair","menu","inicio","configuracoes","configuracao","concluir","finalizar","tentar novamente","ver resposta","responder","avancar","fechar"]);
function nativeBridgeAvailable(){return !!(window.LibrasNative&&typeof window.LibrasNative.getState==="function")}
function getNativeState(){if(!nativeBridgeAvailable())return null;try{let raw=window.LibrasNative.getState(),st=JSON.parse(raw||"{}");try{st.detections=JSON.parse(st.detections||"[]")}catch{st.detections=[]}return st}catch(e){console.warn("bridge",e);return null}}
function personalEditionAvailable(){let st=getNativeState();return !!(st&&st.edition==="personal")}
function applyEditionUI(){let personal=personalEditionAvailable(),section=$("#libraslab"),quick=$("#libraslab-quick"),more=$("#libraslab-more");if(section)section.classList.toggle("hidden",!personal);if(quick)quick.classList.toggle("hidden",!personal);if(more)more.classList.toggle("hidden",!personal);if(!personal&&section?.classList.contains("active"))go("home")}
function llTextVariants(text){let raw=String(text||"").trim().replace(/\s+/g," "),out=[raw];let cleaned=raw.replace(/^(sinal|palavra|resposta|aprenda|pratique)\s*(de|da|do|:|-)?\s*/i,"").trim();if(cleaned&&cleaned!==raw)out.push(cleaned);if(raw.includes(":")){let tail=raw.split(":").slice(1).join(":").trim();if(tail)out.push(tail)}return[...new Set(out.filter(Boolean))]}
async function buildLibrasLabCandidates(raw){await catalog();let map=new Map,owned=new Set(S.signs.map(x=>x.norm));for(let d of(raw||[])){let matched=null;for(let variant of llTextVariants(d.text)){let os=opts(variant);if(os.length){matched={variant,options:os};break}}if(!matched)continue;let canonical=matched.options[0].label.replace(/\d+$/,"").trim()||matched.variant,k=norm(canonical),cur=map.get(k);if(!cur){cur={name:title(canonical),norm:k,count:0,existing:owned.has(k),uiLikely:LL_UI_WORDS.has(k),options:matched.options,raw:[]};map.set(k,cur)}cur.count+=Math.max(1,+d.count||1);if(d.text&&!cur.raw.includes(d.text))cur.raw.push(d.text)}return[...map.values()].sort((a,b)=>(a.uiLikely-b.uiLikely)||(b.count-a.count)||a.name.localeCompare(b.name,"pt-BR"))}
function elapsedText(ts){if(!ts)return"";let sec=Math.max(0,Math.floor((Date.now()-ts)/1000));if(sec<60)return sec+" s";let min=Math.floor(sec/60);if(min<60)return min+" min";let h=Math.floor(min/60),m=min%60;return h+" h"+(m?" "+m+" min":"")}
async function refreshLibrasLab(){applyEditionUI();let warn=$("#ll-not-native"),statusCard=$("#ll-status-card"),sessionCard=$("#ll-session-card"),detCard=$("#ll-detected-card");if(!warn||!statusCard)return;let native=personalEditionAvailable();warn.classList.toggle("hidden",native);statusCard.classList.toggle("hidden",!native);sessionCard.classList.toggle("hidden",!native);if(!native){detCard.classList.add("hidden");return}let st=getNativeState()||{},enabled=!!st.accessibilityEnabled,live=!!st.captureEnabled;$("#ll-accessibility-status").textContent=enabled?"Conectado ao LibrasLab":"Permissão ainda não ativada";$("#ll-accessibility-dot").className="status-dot "+(live?"live":enabled?"ok":"");$("#ll-enable").classList.toggle("hidden",enabled);$("#ll-start").classList.toggle("hidden",live);$("#ll-start").disabled=!enabled;$("#ll-open").classList.toggle("hidden",!live);$("#ll-stop").classList.toggle("hidden",!live);let raw=Array.isArray(st.detections)?st.detections:[];$("#ll-session-info").textContent=live?"🟣 Captura ativa · "+raw.length+" textos únicos lidos · "+elapsedText(st.sessionStartedAt):raw.length?"Aula finalizada. Revise os sinais detectados abaixo.":"Inicie a captura antes de abrir o LibrasLab.";if(!raw.length){detCard.classList.add("hidden");S.librasLabCandidates=[];return}detCard.classList.remove("hidden");$("#ll-detected-list").innerHTML='<div class="ll-progress">🔎 Conferindo '+raw.length+' textos com o catálogo do Studio…</div>';let candidates=await buildLibrasLabCandidates(raw);S.librasLabCandidates=candidates;$("#ll-detected-title").textContent=candidates.length+" "+(candidates.length===1?"sinal":"sinais");$("#ll-detected-meta").textContent=raw.length+" textos lidos do LibrasLab · "+candidates.length+" reconhecidos como sinais no catálogo.";$("#ll-detected-list").innerHTML=candidates.length?candidates.map((c,i)=>'<label class="ll-candidate '+(c.existing?"existing":"")+'"><input type="checkbox" data-ll-index="'+i+'" '+(c.uiLikely?"":"checked")+'><div><b>'+esc(c.name)+'</b><small>'+c.count+' ocorrência(s) · '+(c.existing?"já está na biblioteca":"novo sinal")+(c.uiLikely?" · pode ser botão da interface":"")+'</small></div>'+(c.existing?'<span class="ll-badge">já salvo</span>':"")+'</label>').join(""):'<div class="ll-empty">Ainda não reconheci nomes de sinais nesta sessão. Continue a aula e toque em ↻ Atualizar.</div>'}
function llOpenAccessibility(){if(nativeBridgeAvailable())window.LibrasNative.openAccessibilitySettings()}
function llStart(){if(!nativeBridgeAvailable())return;if(!(getNativeState()?.accessibilityEnabled))return llOpenAccessibility();window.LibrasNative.startLibrasLabCapture();refreshLibrasLab();setTimeout(()=>window.LibrasNative.openLibrasLab(),180)}
function llOpen(){if(nativeBridgeAvailable())window.LibrasNative.openLibrasLab()}
function llStop(){if(!nativeBridgeAvailable())return;window.LibrasNative.stopLibrasLabCapture();setTimeout(refreshLibrasLab,120)}
function llClear(){if(!nativeBridgeAvailable())return;window.LibrasNative.stopLibrasLabCapture();window.LibrasNative.clearLibrasLabDetections();S.librasLabCandidates=[];refreshLibrasLab()}
async function llImport(){if(!S.session)return toast("Entre na sua conta primeiro.");let selected=$$("[data-ll-index]:checked").map(x=>S.librasLabCandidates[+x.dataset.llIndex]).filter(Boolean);if(!selected.length)return toast("Selecione pelo menos um sinal.");$("#ll-import").disabled=true;let added=0,due=0,failed=[];try{for(let c of selected){let existing=S.signs.find(x=>x.norm===c.norm);if(existing){let r=S.reviews.find(x=>x.norm===c.norm);if(r){let now=new Date().toISOString(),patch={due_at:now,updated_at:now};let{error}=await sb.from("review_state").update(patch).eq("user_id",S.session.user.id).eq("norm",c.norm);if(error)throw error;Object.assign(r,patch);due++}continue}let picked=await firstPlayable(c.options,{timeout:3500,max:10});if(!picked){failed.push(c.name);continue}await save(c.name,picked,null,"libraslab_bridge");added++}if(nativeBridgeAvailable()){window.LibrasNative.stopLibrasLabCapture();window.LibrasNative.clearLibrasLabDetections()}cache();render();let msg="✅ "+added+" novo(s) sinal(is) adicionado(s)";if(due)msg+=" · "+due+" revisão(ões) trazidas para agora";if(failed.length)msg+=" · "+failed.length+" sem vídeo disponível";toast(msg);S.librasLabCandidates=[];refreshLibrasLab()}catch(e){console.error(e);toast("Não consegui concluir toda a importação.")}finally{$("#ll-import").disabled=false}}
window.addEventListener("librasstudio-native-resume",()=>refreshLibrasLab());
window.addEventListener("focus",()=>{if($("#libraslab")?.classList.contains("active"))refreshLibrasLab()});
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&$("#libraslab")?.classList.contains("active"))refreshLibrasLab()});
function installNativeTouchNavigation(){
  if(!IS_NATIVE_ANDROID||window.__lsNativeTouchNav)return;
  window.__lsNativeTouchNav=true;
  document.addEventListener("pointerup",e=>{
    if(e.pointerType&&e.pointerType!=="touch")return;
    const nav=e.target.closest("nav [data-view]");
    if(nav){
      e.preventDefault();
      const v=nav.dataset.view;
      nav.dataset.nativeTapAt=String(Date.now());
      if(v==="more"){
        const sheet=$("#more");
        if(sheet)sheet.classList.remove("hidden");
      }else go(v);
      return;
    }
    const quick=e.target.closest("[data-go]");
    if(quick){
      e.preventDefault();
      go(quick.dataset.go);
    }
  },{passive:false});
}
function installDelegatedNavigation(){
  if(window.__lsDelegatedNav)return;window.__lsDelegatedNav=true;
  document.addEventListener("click",e=>{
    const cat=e.target.closest("[data-home-cat],[data-cat]");
    if(cat){e.preventDefault();let name=cat.dataset.homeCat||cat.dataset.cat;if(cat.dataset.homeCat){go("explore");setTimeout(()=>openCat(name),0)}else openCat(name);return}
    const nav=e.target.closest("[data-go]");
    if(nav){e.preventDefault();go(nav.dataset.go)}
  });
}
function wire(){$("#auth-form").onsubmit=async e=>{e.preventDefault();let{error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});$("#auth-status").textContent=error?error.message:""};$("#signup").onclick=async()=>{let{error}=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});$("#auth-status").textContent=error?error.message:"Conta criada. Confira seu e-mail."};$("#logout").onclick=async()=>{try{await sb.auth.signOut({scope:"local"})}finally{forgetRememberedUser();S.session=null;S.signs=[];S.cats=[];S.reviews=[];S.study=[];authUI()}};$("#sync").onclick=$("#sync-now").onclick=sync;$("#app-update").onclick=$("#update-now").onclick=forceAppUpdate;let mu=$("#mobile-update-now");if(mu)mu.onclick=forceAppUpdate;$("#ll-enable").onclick=llOpenAccessibility;$("#ll-start").onclick=llStart;$("#ll-open").onclick=llOpen;$("#ll-stop").onclick=llStop;$("#ll-refresh").onclick=refreshLibrasLab;$("#ll-import").onclick=llImport;$("#ll-clear").onclick=llClear;$$("nav [data-view]").forEach(b=>b.onclick=()=>{if(IS_NATIVE_ANDROID&&Date.now()-Number(b.dataset.nativeTapAt||0)<700)return;if(b.dataset.view==="more"){let s=$("#more");if(s)s.classList.toggle("hidden")}else go(b.dataset.view)});$$(".side-nav [data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));$$("[data-mode]").forEach(b=>b.onclick=()=>{$$("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));$("#sign-box").classList.toggle("hidden",b.dataset.mode!=="sign");$("#phrase-box").classList.toggle("hidden",b.dataset.mode!=="phrase")});$("#create-search").onclick=createSign;$("#variants").onclick=variants;$("#video-file").onchange=e=>uploadVideo(e.target.files[0]);$("#phrase-search")&&($("#phrase-search").onclick=phrase);$("#explore-search").oninput=exploreCats;$("#global-search").onkeydown=e=>{if(e.key==="Enter"){let q=e.currentTarget.value.trim();go("explore");$("#create-name").value=q;$("#create-name").focus()}};$("#study-search").oninput=study;$("#library-search").oninput=library;$("#library-cat").onchange=library;$("#new-cat").onclick=newCat;$("#move").onclick=move;$("#delete").onclick=del;$("#review-start").onclick=()=>{S.queue=queue();S.i=0;$("#review-setup").classList.add("hidden");card()};$("#reveal").onclick=()=>{$("#review-media").classList.remove("hidden");$("#ratings").classList.remove("hidden");$("#reveal").classList.add("hidden")};$$("[data-rate]").forEach(b=>b.onclick=()=>rate(b.dataset.rate));$("#again-session").onclick=()=>{$("#review-setup").classList.remove("hidden");$("#review-done").classList.add("hidden")};$("#close-modal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#modal").classList.add("hidden")}}
async function revalidateSessionAndSync(){
  if(!navigator.onLine){localStatus("📴 offline · dados locais");return}
  try{
    let{data:{session},error}=await sb.auth.getSession();
    if(error)throw error;
    if(session){S.session=session;rememberSession(session);cached(session.user.id);authUI();await sync({silent:true})}
    else if(S.session?.offline){forgetRememberedUser();S.session=null;authUI()}
  }catch(e){console.warn("revalidar sessão",e);if(S.session)localStatus("📴 dados locais")}
}
async function init(){
  let remembered=rememberedUser();
  if(remembered){
    S.session=offlineSession(remembered);
    cached(remembered.id);
    authUI();render();
    localStatus(navigator.onLine?"☁️ dados locais":"📴 offline · dados locais");
  }
  sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:!IS_NATIVE_ANDROID,storage:window.localStorage}});
  wire();installDelegatedNavigation();if(window.LSHydrateIcons)LSHydrateIcons(document);installNativeTouchNavigation();applyEditionUI();
  sb.auth.onAuthStateChange((event,session)=>{
    if(session){
      S.session=session;rememberSession(session);cached(session.user.id);authUI();
      if(navigator.onLine)setTimeout(()=>sync({silent:true}),0);
    }else if(event==="SIGNED_OUT"){
      forgetRememberedUser();S.session=null;S.signs=[];S.cats=[];S.reviews=[];S.study=[];authUI();
    }
  });
  try{
    let{data:{session},error}=await sb.auth.getSession();
    if(error)throw error;
    if(session){S.session=session;rememberSession(session);cached(session.user.id);authUI();if(navigator.onLine)sync({silent:true});else localStatus("📴 offline · dados locais")}
    else if(!remembered){S.session=null;authUI()}
    else if(navigator.onLine){forgetRememberedUser();S.session=null;authUI()}
  }catch(e){console.warn("sessão inicial",e);if(S.session){cached();render();localStatus("📴 dados locais")}else authUI()}
  window.addEventListener("online",()=>{localStatus("☁️ reconectando…");revalidateSessionAndSync()});
  window.addEventListener("offline",()=>{if(S.session){cached();render();localStatus("📴 offline · dados locais")}});
  setupServiceWorker();
  checkAppUpdate();
}init();