const cfg=window.LIBRAS_STUDIO_CONFIG||{},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let sb,S={session:null,signs:[],cats:[],reviews:[],study:[],catalog:null,queue:[],i:0,explore:null};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();
const title=s=>{s=String(s||"").trim().replace(/\s+/g," ");return s?s[0].toLocaleUpperCase("pt-BR")+s.slice(1).toLocaleLowerCase("pt-BR"):s};
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");clearTimeout(x._t);x._t=setTimeout(()=>x.classList.remove("show"),2500)}
function go(v){$$(".view").forEach(x=>x.classList.remove("active"));$("#"+v).classList.add("active");$$("nav [data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#more").classList.add("hidden");scrollTo(0,0)}
function authUI(){let on=!!S.session;$("#auth").classList.toggle("hidden",on);$("#app").classList.toggle("hidden",!on);if(on)$("#account").textContent="☁️ "+S.session.user.email}
function cache(){localStorage.setItem("ls-full",JSON.stringify({signs:S.signs,cats:S.cats,reviews:S.reviews,study:S.study}))}
function cached(){try{let x=JSON.parse(localStorage.getItem("ls-full")||"{}");S.signs=x.signs||[];S.cats=x.cats||[];S.reviews=x.reviews||[];S.study=x.study||[]}catch{}}
async function sync(){if(!S.session)return;$("#sync-status").textContent="sincronizando…";try{let[c,s,r,p]=await Promise.all([sb.from("categories").select("*").is("deleted_at",null).order("sort_order"),sb.from("signs").select("*").is("deleted_at",null).order("name"),sb.from("review_state").select("*").is("deleted_at",null),sb.from("study_progress").select("*")]);for(let x of[c,s,r,p])if(x.error)throw x.error;S.cats=c.data||[];S.signs=s.data||[];S.reviews=r.data||[];S.study=p.data||[];await signMedia();cache();render();$("#sync-status").textContent="☁️ sincronizado"}catch(e){console.error(e);cached();render();$("#sync-status").textContent="offline"}}
async function signMedia(){for(let s of S.signs){if(s.media_path&&!s.media_url){let z=await sb.storage.from("sign-videos").createSignedUrl(s.media_path,86400);if(z.data?.signedUrl)s.media_url=z.data.signedUrl}}}
function render(){home();library();reviewCats();study();exploreCats()}
function unique(){let m=new Map;S.signs.forEach(s=>{if(!m.has(s.norm))m.set(s.norm,s)});return[...m.values()]}
function rmap(){return Object.fromEntries(S.reviews.map(x=>[x.norm,x]))}
function home(){let m=rmap(),now=Date.now(),u=unique(),d=0,n=0;u.forEach(s=>{let r=m[s.norm];if(!r)n++;else if(r.due_at&&new Date(r.due_at).getTime()<=now)d++});$("#due").textContent=d;$("#fresh").textContent=n;$("#total").textContent=u.length}
const SRC=[["signbank","SignBank / UFSC","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_ufsc_signbank.csv"],["ines","INES / Acessibilidade Brasil","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_acessibilidade_brasil.csv"],["ufv","UFV","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_ufv.csv"],["usp","USP","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_usp.csv"],["spread","Spread the Sign","https://raw.githubusercontent.com/Malta-Lab/ISLR_LIBRAS/main/video_downloads/links_videos_spreadthesign.csv"]];
function csvLine(l){let a=[],x="",q=false;for(let i=0;i<l.length;i++){let c=l[i];if(c=='"'){if(q&&l[i+1]=='"'){x+='"';i++}else q=!q}else if(c==","&&!q){a.push(x);x=""}else x+=c}a.push(x);return a}
async function catalog(){if(S.catalog)return S.catalog;$("#sync-status").textContent="abrindo catálogo…";let map={};for(let[id,name,url]of SRC){try{let t=await fetch(url).then(r=>r.text()),ls=t.split(/\r?\n/);for(let i=1;i<ls.length;i++){if(!ls[i])continue;let a=csvLine(ls[i]),label=a[0]?.trim(),u=a[1]?.trim();if(!label||!u)continue;let k=norm(label.replace(/\d+$/,""));(map[k]??=[]).push({label,url:u.replace(/^http:/,"https:"),source_id:id,source_name:name})}}catch(e){console.warn(e)}}S.catalog=map;$("#sync-status").textContent="☁️ sincronizado";return map}
const opts=n=>(S.catalog||{})[norm(n)]||[];
function catFor(n){let k=norm(n);for(let[c,d]of Object.entries(window.LIBRAS_EXPLORE_DATA||{}))if(d.terms.some(x=>norm(x)===k))return c;return"Outros"}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
async function save(name,o,cat=null,origin="catalog"){let n=norm(name),row={user_id:S.session.user.id,studio_id:uuid(),name:title(name),norm:n,variant_no:S.signs.filter(x=>x.norm===n).length+1,variant_key:"mobile|"+n+"|"+norm(o.url),category_name:cat||catFor(name),category_source:cat?"explore":"auto",category_tags:"[]",source_id:o.source_id,source_name:o.source_name,source_url:o.url,source_label:o.label,origin,media_url:o.url,updated_at:new Date().toISOString()},{data,error}=await sb.from("signs").insert(row).select().single();if(error)throw error;S.signs.push(data);cache();render();return data}
async function createSign(){let n=$("#create-name").value.trim();if(!n)return toast("Digite o nome do sinal.");$("#create-result").innerHTML='<div class="result">Buscando…</div>';await catalog();let o=opts(n);if(!o.length)return $("#create-result").innerHTML='<div class="result">🔎 Não encontrei correspondência exata.</div>';try{let r=await save(n,o[0]);$("#create-result").innerHTML='<div class="result"><b>✅ '+esc(r.name)+'</b><small> · '+esc(r.source_name)+'</small><video controls loop playsinline src="'+esc(r.media_url)+'"></video></div>';toast("Salvo e sincronizado ☁️")}catch(e){toast("Não consegui salvar.")}}
async function variants(){let n=$("#create-name").value.trim();if(!n)return toast("Digite um sinal primeiro.");await catalog();let o=opts(n);if(!o.length)return toast("Nenhuma variação encontrada.");modal('<h2>🎞 Variações de '+esc(title(n))+'</h2>'+o.slice(0,20).map((x,i)=>'<div class="variant"><div class="variant-head"><div><b>'+esc(x.source_name)+'</b><small>'+esc(x.label)+'</small></div><button class="soft" data-var="'+i+'">＋ Salvar</button></div><video controls loop playsinline src="'+esc(x.url)+'"></video></div>').join(""));$$("[data-var]").forEach(b=>b.onclick=async()=>{b.disabled=true;try{await save(n,o[+b.dataset.var]);b.textContent="✓ Salva"}catch{b.disabled=false;toast("Falha ao salvar")}})}
async function uploadVideo(f){if(!f)return;let n=$("#create-name").value.trim();if(!n)return toast("Digite o nome antes.");let path=S.session.user.id+"/"+Date.now()+"_"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_"),up=await sb.storage.from("sign-videos").upload(path,f);if(up.error)return toast("Falha no upload.");let row={user_id:S.session.user.id,studio_id:uuid(),name:title(n),norm:norm(n),variant_no:S.signs.filter(x=>x.norm===norm(n)).length+1,variant_key:"upload|"+path,category_name:catFor(n),category_source:"auto",category_tags:"[]",source_id:"mobile_upload",source_name:"Vídeo meu",origin:"mobile_upload",media_path:path,updated_at:new Date().toISOString()},{data,error}=await sb.from("signs").insert(row).select().single();if(error)return toast(error.message);let z=await sb.storage.from("sign-videos").createSignedUrl(path,86400);data.media_url=z.data?.signedUrl;S.signs.push(data);render();toast("Vídeo enviado ☁️")}
const PH={"como cumprimentar":"https://www.singlibras.com/dicionario/clipes/como-cumprimentar-v2.mp4","como dizer as horas":"https://www.singlibras.com/dicionario/clipes/como-dizer-as-horas-v2.mp4","desculpa":"https://www.singlibras.com/dicionario/clipes/desculpa-v2.mp4","eu amo minha familia":"https://www.singlibras.com/dicionario/clipes/eu-amo-minha-familia-v2.mp4","eu te amo":"https://www.singlibras.com/dicionario/clipes/eu-te-amo-v2.mp4","eu vou":"https://www.singlibras.com/dicionario/clipes/eu-vou-v2.mp4"};
async function phrase(){let n=$("#phrase-name").value.trim(),u=PH[norm(n)];if(!u)return $("#phrase-result").innerHTML='<div class="result">🔎 Não encontrei uma gravação contínua exata. O Studio não monta frases artificialmente.</div>';try{let r=await save(n,{url:u,label:n,source_id:"singlibras_phrase",source_name:"Sing Libras · Frases"},"Frases","phrase_complete");$("#phrase-result").innerHTML='<div class="result"><b>✅ '+esc(r.name)+'</b><video controls loop src="'+u+'"></video></div>'}catch{toast("Falha ao salvar")}}
async function batch(){let ns=$("#batch-text").value.split(/\n|,/).map(x=>x.trim()).filter(Boolean),ok=0,fail=[];await catalog();for(let n of ns){let o=opts(n);if(!o.length){fail.push(n);continue}try{await save(n,o[0],null,"batch");ok++}catch{fail.push(n)}}$("#batch-result").innerHTML='<div class="result"><b>✅ '+ok+' salvos</b>'+(fail.length?'<p>Não encontrados: '+esc(fail.join(", "))+'</p>':"")+"</div>"}
function exploreCats(){let q=norm($("#explore-search")?.value),D=window.LIBRAS_EXPLORE_DATA||{};$("#explore-cats").innerHTML=Object.entries(D).filter(([c,d])=>!q||norm(c+" "+d.description).includes(q)).map(([c,d])=>'<button data-cat="'+esc(c)+'" class="'+(S.explore===c?"active":"")+'">'+d.emoji+" "+esc(c)+"</button>").join("");$$("[data-cat]").forEach(b=>b.onclick=()=>openCat(b.dataset.cat))}
async function openCat(c){S.explore=c;exploreCats();await catalog();let d=window.LIBRAS_EXPLORE_DATA[c],owned=new Set(S.signs.map(x=>x.norm)),rows=d.terms.map(t=>({t,o:opts(t),owned:owned.has(norm(t))})).filter(x=>x.o.length);$("#explore-panel").innerHTML='<div class="card"><h3>'+d.emoji+" "+esc(c)+'</h3><p>'+esc(d.description)+'</p><button id="all-missing" class="primary wide">⬇ Adicionar tudo que falta</button></div>'+rows.map((r,i)=>'<div class="explore-row"><div><b>'+esc(title(r.t))+'</b><small>'+r.o.length+" gravação(ões) · "+(r.owned?"✓ na biblioteca":esc(r.o[0].source_name))+'</small></div>'+(r.owned?"✓":'<button data-add="'+i+'">＋</button>')+"</div>").join("");$$("[data-add]").forEach(b=>b.onclick=async()=>{let r=rows[+b.dataset.add];try{await save(r.t,r.o[0],c,"category_explorer");b.textContent="✓";b.disabled=true}catch{toast("Falha")}});$("#all-missing").onclick=async()=>{let n=0;for(let r of rows.filter(x=>!x.owned))try{await save(r.t,r.o[0],c,"category_explorer");n++}catch{}toast(n+" sinais adicionados");openCat(c)}}
function smap(){return Object.fromEntries(S.study.map(x=>[x.lesson_id,x]))}
function study(){let L=window.LIBRAS_STUDY_CONTENT||[],m=smap(),done=L.filter(x=>m[x.id]?.completed).length;$("#study-count").textContent=done+" de "+L.length+" aulas";$("#study-pct").textContent=Math.round(done/Math.max(1,L.length)*100)+"%";let mods=[...new Set(L.map(x=>x.module))],a=$("#study-modules").dataset.active||"";$("#study-modules").innerHTML='<button data-mod="" class="'+(!a?"active":"")+'">Todas</button>'+mods.map(x=>'<button data-mod="'+esc(x)+'" class="'+(a===x?"active":"")+'">'+esc(x)+"</button>").join("");$$("[data-mod]").forEach(b=>b.onclick=()=>{$("#study-modules").dataset.active=b.dataset.mod;study()});let q=norm($("#study-search").value),F=L.filter(x=>(!a||x.module===a)&&(!q||norm(x.title+" "+x.summary).includes(q)));$("#study-list").innerHTML=F.map(x=>'<article class="lesson"><small>'+x.icon+" "+esc(x.module)+" · "+esc(x.level)+'</small><h3>'+esc(x.title)+'</h3><p>'+esc(x.summary)+'</p>'+x.sections.map(s=>'<h4>'+esc(s[0])+'</h4><p>'+esc(s[1])+"</p>").join("")+'<div class="practice"><b>🧪 Prática</b><p>'+esc(x.practice)+'</p></div><ul>'+x.take.map(t=>"<li>"+esc(t)+"</li>").join("")+"</ul>"+(x.resources||[]).map(r=>'<a class="resource" href="'+esc(r[1])+'" target="_blank">↗ '+esc(r[0])+"</a>").join("")+'<label class="complete"><input type="checkbox" data-lesson="'+x.id+'" '+(m[x.id]?.completed?"checked":"")+'> Aula concluída</label></article>').join("");$$("[data-lesson]").forEach(c=>c.onchange=()=>saveLesson(c.dataset.lesson,c.checked))}
async function saveLesson(id,v){let row={user_id:S.session.user.id,lesson_id:id,completed:v,completed_at:v?new Date().toISOString():null,updated_at:new Date().toISOString()},{error}=await sb.from("study_progress").upsert(row,{onConflict:"user_id,lesson_id"});if(error)return toast("Falha ao salvar.");let i=S.study.findIndex(x=>x.lesson_id===id);if(i>=0)S.study[i]=row;else S.study.push(row);cache();study()}
function vurl(s){return s.media_url||(s.source_url&&/\.mp4($|\?)/i.test(s.source_url)?s.source_url.replace(/^http:/,"https:"):"")}
function library(){let q=norm($("#library-search").value),g={};S.signs.filter(s=>!q||norm(s.name+" "+s.category_name).includes(q)).forEach(s=>(g[s.category_name||"Outros"]??=[]).push(s));$("#library-list").innerHTML=Object.entries(g).sort().map(([c,it])=>'<div><div class="cat-head"><span>'+(S.cats.find(x=>x.name===c)?.emoji||"🧩")+" "+esc(c)+'</span><span>'+new Set(it.map(x=>x.norm)).size+"</span></div>"+it.map(x=>'<div class="lib-row"><input type="checkbox" data-sel="'+x.studio_id+'"><div><b>'+esc(x.name)+'</b><small>'+esc(x.source_name||"Libras Studio")+(x.variant_no>1?" · V"+x.variant_no:"")+'</small></div>'+(vurl(x)?'<button data-play="'+x.studio_id+'">▶</button>':"")+"</div>").join("")+"</div>").join("");$$("[data-play]").forEach(b=>b.onclick=()=>{let s=S.signs.find(x=>x.studio_id===b.dataset.play);modal("<h2>"+esc(s.name)+'</h2><video controls autoplay loop src="'+esc(vurl(s))+'"></video><p>'+esc(s.source_name||"")+"</p>")})}
const selected=()=>$$("[data-sel]:checked").map(x=>x.dataset.sel);
async function newCat(){let n=prompt("Nome da categoria:");if(!n)return;let e=prompt("Emoji:","🧩")||"🧩",row={user_id:S.session.user.id,name:title(n),emoji:e,sort_order:999,is_custom:true,is_hidden:false,updated_at:new Date().toISOString()},{data,error}=await sb.from("categories").insert(row).select().single();if(error)return toast(error.message);S.cats.push(data);render()}
async function move(){let ids=selected();if(!ids.length)return toast("Selecione sinais.");let names=S.cats.map(x=>x.name),c=prompt("Mover para qual categoria?\n\n"+names.join("\n"));if(!names.includes(c))return;let{error}=await sb.from("signs").update({category_name:c,category_source:"manual",updated_at:new Date().toISOString()}).in("studio_id",ids);if(error)return toast(error.message);S.signs.forEach(x=>{if(ids.includes(x.studio_id))x.category_name=c});library()}
async function del(){let ids=selected();if(!ids.length||!confirm("Excluir "+ids.length+" item(ns)?"))return;let now=new Date().toISOString(),{error}=await sb.from("signs").update({deleted_at:now,updated_at:now}).in("studio_id",ids);if(error)return toast(error.message);S.signs=S.signs.filter(x=>!ids.includes(x.studio_id));render()}
function reviewCats(){let s=$("#review-cat"),v=s.value,cs=[...new Set(S.signs.map(x=>x.category_name).filter(Boolean))].sort();s.innerHTML='<option value="">Todas</option>'+cs.map(x=>'<option>'+esc(x)+"</option>").join("");s.value=v}
function next(rate,c){let reps=c?.reps||0,e=c?.ease||2.5,iv=+c?.interval_days||0,d=0,l=c?.lapses||0,n=reps;if(rate==="again"){d=10/1440;e=Math.max(1.3,e-.2);l++}if(rate==="hard"){d=reps?Math.max(1,iv*1.2):.25;e=Math.max(1.3,e-.15);n++}if(rate==="good"){d=reps===0?1:reps===1?3:Math.max(1,iv*e);n++}if(rate==="easy"){e=Math.min(3.5,e+.15);d=reps?Math.max(2,iv*(e+.3)):4;n++}return{interval_days:d,ease:e,reps:n,lapses:l,due_at:new Date(Date.now()+d*864e5).toISOString()}}
function queue(){let c=$("#review-cat").value,mode=$("#review-mode").value,m=rmap(),now=Date.now(),due=[],fresh=[];unique().filter(s=>!c||s.category_name===c).forEach(s=>{let r=m[s.norm];if(!r)fresh.push(s);else if(r.due_at&&new Date(r.due_at).getTime()<=now)due.push(s)});return(mode==="due"?due:mode==="new"?fresh:[...due,...fresh]).slice(0,+$("#review-limit").value)}
function card(){let s=S.queue[S.i];if(!s){$("#review-card").classList.add("hidden");$("#review-done").classList.remove("hidden");return}$("#review-card").classList.remove("hidden");$("#review-done").classList.add("hidden");$("#review-name").textContent=s.name;$("#review-media").classList.add("hidden");$("#ratings").classList.add("hidden");$("#reveal").classList.remove("hidden");let vs=S.signs.filter(x=>x.norm===s.norm&&vurl(x));$("#review-media").innerHTML=vs.length?vs.map((v,i)=>'<video controls loop src="'+esc(vurl(v))+'"></video><small>'+(vs.length>1?"Variação "+(i+1)+" · ":"")+esc(v.source_name||"")+"</small>").join(""):"<p>Vídeo indisponível.</p>"}
async function rate(r){let s=S.queue[S.i],row={user_id:S.session.user.id,norm:s.norm,...next(r,rmap()[s.norm]),last_rating:r,last_reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{error}=await sb.from("review_state").upsert(row,{onConflict:"user_id,norm"});if(error)return toast("Falha ao salvar.");let i=S.reviews.findIndex(x=>x.norm===s.norm);if(i>=0)S.reviews[i]=row;else S.reviews.push(row);S.i++;cache();home();card()}
function modal(h){$("#modal-body").innerHTML=h;$("#modal").classList.remove("hidden")}
function wire(){$("#auth-form").onsubmit=async e=>{e.preventDefault();let{error}=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});$("#auth-status").textContent=error?error.message:""};$("#signup").onclick=async()=>{let{error}=await sb.auth.signUp({email:$("#email").value,password:$("#password").value});$("#auth-status").textContent=error?error.message:"Conta criada. Confira seu e-mail."};$("#logout").onclick=()=>sb.auth.signOut({scope:"local"});$("#sync").onclick=$("#sync-now").onclick=sync;$$("nav [data-view]").forEach(b=>b.onclick=()=>b.dataset.view==="more"?$("#more").classList.toggle("hidden"):go(b.dataset.view));$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));$$("[data-mode]").forEach(b=>b.onclick=()=>{$$("[data-mode]").forEach(x=>x.classList.toggle("active",x===b));$("#sign-box").classList.toggle("hidden",b.dataset.mode!=="sign");$("#phrase-box").classList.toggle("hidden",b.dataset.mode!=="phrase")});$("#create-search").onclick=createSign;$("#variants").onclick=variants;$("#video-file").onchange=e=>uploadVideo(e.target.files[0]);$("#phrase-search").onclick=phrase;$("#batch-run").onclick=batch;$("#explore-search").oninput=exploreCats;$("#study-search").oninput=study;$("#library-search").oninput=library;$("#new-cat").onclick=newCat;$("#move").onclick=move;$("#delete").onclick=del;$("#review-start").onclick=()=>{S.queue=queue();S.i=0;$("#review-setup").classList.add("hidden");card()};$("#reveal").onclick=()=>{$("#review-media").classList.remove("hidden");$("#ratings").classList.remove("hidden");$("#reveal").classList.add("hidden")};$$("[data-rate]").forEach(b=>b.onclick=()=>rate(b.dataset.rate));$("#again-session").onclick=()=>{$("#review-setup").classList.remove("hidden");$("#review-done").classList.add("hidden")};$("#close-modal").onclick=()=>$("#modal").classList.add("hidden");$("#modal").onclick=e=>{if(e.target===$("#modal"))$("#modal").classList.add("hidden")}}
async function init(){if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);let{data:{session}}=await sb.auth.getSession();S.session=session;sb.auth.onAuthStateChange((_e,s)=>{S.session=s;authUI();if(s)sync()});authUI();wire();if(session)await sync()}init();