window.LIBRAS_EXPLORE_DATA={
"Família":["👨‍👩‍👧‍👦","Parentes e relações","familia mae mamae pai papai pais filho filha irmao irma avo avos tio tia sobrinho sobrinha primo prima marido esposa namorado namorada noivo noiva sogro sogra neto neta casamento divorcio"],
"Cores":["🎨","Cores e tons","vermelho azul verde amarelo laranja roxo violeta lilas rosa preto branco cinza marrom bege dourado prata"],
"Números e quantidades":["🔢","Números, ordem e quantidade","zero um dois tres quatro cinco seis sete oito nove dez onze doze treze quatorze quinze vinte trinta quarenta cinquenta cem mil primeiro segundo terceiro metade dobro quantidade"],
"Perguntas":["❓","Palavras interrogativas","como quem onde aonde quando qual quais quanto quantos quantas cade"],
"Pessoas e pronomes":["🧑","Pessoas e grupos","eu voce ele ela nos voces eles elas pessoa homem mulher menino menina crianca adulto jovem idoso bebe amigo colega"],
"Saudações e cortesia":["👋","Cumprimentos e expressões sociais","oi ola tchau obrigado obrigada por favor desculpa licenca prazer parabens bom dia boa tarde boa noite"],
"Tempo e calendário":["📅","Dias, meses e horários","hoje ontem amanha agora depois antes cedo tarde noite manha semana mes ano dia hora minuto segunda terca quarta quinta sexta sabado domingo"],
"Casa e objetos":["🏠","Ambientes e objetos","casa apartamento quarto sala cozinha banheiro garagem porta janela mesa cadeira cama sofa armario geladeira fogao copo prato chave lampada"],
"Alimentos e bebidas":["🍽️","Comidas e refeições","comida comer bebida beber agua cafe leite suco arroz feijao carne frango peixe ovo pao queijo bolo fruta banana maca almoco jantar fome sede"],
"Animais":["🐾","Animais","cachorro gato passaro peixe cavalo vaca boi porco galinha coelho rato macaco leao tigre elefante cobra sapo tartaruga"],
"Corpo humano":["🫶","Partes do corpo","cabeca rosto olho nariz boca dente lingua orelha cabelo pescoco ombro braco cotovelo mao dedo peito barriga costas perna joelho pe"],
"Saúde e cuidados":["🩺","Saúde e sintomas","saude doente doenca dor medico hospital remedio farmacia febre gripe tosse sangue vacina consulta tratamento acidente cansado dormir"],
"Roupas e acessórios":["👕","Vestuário","roupa camisa camiseta calca short vestido saia casaco sapato tenis sandalia meia bone chapeu oculos relogio bolsa cinto"],
"Escola e estudo":["🎓","Aprendizagem","escola universidade faculdade aluno professor aula estudar aprender ensinar prova atividade caderno livro lapis caneta pergunta resposta curso libras"],
"Trabalho e profissões":["💼","Trabalho e profissões","trabalho trabalhar emprego profissao chefe empresa banco escritorio salario medico professor advogado engenheiro enfermeiro motorista vendedor"],
"Lugares":["📍","Lugares","cidade bairro rua praca parque praia mercado shopping loja escola faculdade hospital farmacia banco igreja restaurante hotel aeroporto cinema"],
"Transporte e trânsito":["🚌","Mobilidade","carro moto bicicleta onibus metro trem aviao barco taxi transporte dirigir motorista passagem viagem estrada transito semaforo parar"],
"Natureza e clima":["🌿","Natureza e clima","sol lua estrela ceu nuvem chuva vento calor frio arvore flor planta mar rio lago montanha terra fogo agua praia floresta"],
"Sentimentos e emoções":["💛","Emoções","feliz triste raiva medo vergonha amor amar gostar odio saudade preocupado ansiedade calmo nervoso surpresa orgulho ciume"],
"Características e estados":["✨","Qualidades e estados","grande pequeno alto baixo bonito feio novo velho bom ruim facil dificil rapido lento forte fraco cheio vazio aberto fechado limpo sujo caro barato diferente igual"],
"Ações e verbos":["🏃","Ações","fazer ir vir chegar sair entrar ficar ter querer poder precisar dar pegar colocar tirar abrir fechar ver olhar falar dizer perguntar responder conhecer saber pensar entender escolher procurar encontrar comprar vender pagar usar ajudar esperar correr andar sentar levantar trabalhar estudar dormir acordar"],
"Comunicação e língua":["💬","Língua e comunicação","falar conversar comunicar lingua idioma palavra frase nome sinal libras portugues legenda traducao interprete entender repetir explicar pergunta resposta significado"],
"Tecnologia e mídia":["💻","Tecnologia","computador notebook celular telefone internet wifi aplicativo programa site video foto camera youtube mensagem whatsapp instagram jogo teclado mouse"],
"Lazer e esportes":["⚽","Lazer e esporte","jogar jogo futebol volei basquete tenis natacao correr academia exercicio esporte musica cantar dancar filme serie cinema viajar passeio festa guitarra violao"],
"Dinheiro e compras":["🛍️","Compras e pagamentos","dinheiro real preco valor comprar vender pagar pix cartao credito debito banco moeda barato caro desconto loja mercado shopping conta"],
"Rotina diária":["🕒","Hábitos","acordar levantar banho escovar vestir arrumar cafe manha almoco jantar trabalhar estudar descansar dormir"],
"Viagens e turismo":["✈️","Viagens","viagem viajar turismo mala bagagem passaporte hotel aeroporto rodoviaria passagem embarque passeio destino mapa"],
"Emergência e segurança":["🚨","Emergências","emergencia socorro perigo seguro seguranca acidente policia bombeiro ambulancia hospital ajuda urgente cuidado alerta"],
"Acessibilidade e inclusão":["♿","Acessibilidade","acessibilidade inclusao surdo surda ouvinte libras interprete legenda comunidade deficiencia"],
"Relacionamentos":["💞","Vínculos","amizade amigo amiga relacionamento namorado namorada noivo noiva casal parceiro marido esposa encontro amor gostar"],
"Outros":["🧩","Outros sinais","sim nao talvez sempre nunca certo errado"]
};for(const k in window.LIBRAS_EXPLORE_DATA){let x=window.LIBRAS_EXPLORE_DATA[k];window.LIBRAS_EXPLORE_DATA[k]={emoji:x[0],description:x[1],terms:x[2].split(/\s+/)}}